### ISSUE TITLE
Ingen 'ström' för 'http://www.svtplay.se/video/9134966/en-liten-fransk-stad/en-liten-fransk-stad-sasong-4-avsnitt-1'

### ISSUE THREAD

**Issue by BerndtRing** [stefansundin/privatkopiera#1]
http://www.svtplay.se/video/9134966/en-liten-fransk-stad/en-liten-fransk-stad-sasong-4-avsnitt-1

**Comment by stefansundin** [comment]
Verkar som att de har ändrat hur det fungerar, jag släpper nog en uppdatering under helgen.

Så här kan du arbeta runt det så länge. Exakta instruktioner varierar beroende på om du använder Chrome eller Firefox.

1. Öppna utvecklingsverktygen, gå panelen där du kan se nätverkstrafik.
2. Filterera på "videoplayer-api".
3. Ladda om hemsidan.
4. Du borde se en förfrågan när sidan har laddat färdigt.
5. Öppna den och leta efter "videoReferences".
6. Kopiera en m3u8 url och klistra in det i ett kommando ungefär såhär:

```
ffmpeg -i "http://url.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "filnamn.mp4"
```

**Comment by stefansundin** [comment]
Det verkar som att de ändrade tillbaka så att det fungerar igen. Det verkar ta lite längre tid än förut att få videoinformationen, men det fungerar.
