### ISSUE TITLE
Kan ej Ladda ned något från svt

### ISSUE THREAD

**Issue by spirit03** [stefansundin/privatkopiera#100]
![image](https://user-images.githubusercontent.com/80962315/137587552-57495b1b-bebd-4a49-9e57-789566598b74.png)
Hej! 
Får bara detta meddelande när jag laddar ner, vet ej vad som är fel.

Detta är kommandot: 
ffmpeg -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/hls-video-avc-1920x1080p25-3089/hls-video-avc-1920x1080p25-3089.m3u8" -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/hls-audio-aac-2ch-192/hls-audio-aac-2ch-192.m3u8" -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/text/text-0.vtt" -vcodec copy -acodec copy "30 minuter - Avsnitt 6.mkv"

**Comment by TherealGenius** [comment]
laddade alltså ner filen med namnet "ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip"
ifrån https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-11-07-12-25

det kommando jag alltså då använde var är detta

ffmpeg -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/hls-video-avc-1920x1080p25-3089/hls-video-avc-1920x1080p25-3089.m3u8" -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/hls-audio-aac-2ch-192/hls-audio-aac-2ch-192.m3u8" -i "https://svt-vod-5h.akamaized.net/d0/world/20211013/2fce322b-e900-47fe-a817-047244f1161f/text/text-0.vtt" -vcodec copy -acodec copy "30 minuter - Avsnitt 6.mkv"  


den gick till 100%
bifogar om så krävs även output ifrån cmd
