### ISSUE TITLE
Problem med Urplay + firefox v93

### ISSUE THREAD

**Issue by La8p** [stefansundin/privatkopiera#103]
![2021-10-29 15_08_23-](https://user-images.githubusercontent.com/93387057/139440912-da232719-304a-4b8f-8945-a38781b79e23.png)
Verkar som om urplay har varit inne och gjort någon förändring i dagarna, så det bara står "laddar var god vänta". Kör PC med Firefox ver 93 + 0.3.6.  har provat en handfull titlar men får samma problem kopplat till URPlay.

**Comment by mrbanco** [comment]
Jag har också noterat att URPlay inte funkar som förväntat längre.....

**Comment by Tigerfluga** [comment]
För mig är det exakt samma problem som på bilden. Jag använder Chrome och det står bara hela tiden att den laddar men det händer aldrig något.

**Comment by stefansundin** [comment]
Hej. Släpper ny version inom kort som fixar UR och NRK.

**Comment by stefansundin** [comment]
Nu är v0.3.7 släppt och det ska fungera igen. Det kan ta ett tag innan uppdateringen godkänns för Chrome, men det är redan ute till Firefox.
