### ISSUE TITLE
Urplay.se

### ISSUE THREAD

**Issue by gugge59** [stefansundin/privatkopiera#104]
Fungerar inte med Firefox eller Chrome

**Comment by emwtur** [comment]
motsvarande problem fixades så här i kodi - retrospective - 
https://github.com/retrospect-addon/plugin.video.retrospect/commit/e08fd81f8366e33d953353140a6185d9f6c6646c
puthon kod men ...

**Comment by lysol90** [comment]
Tänkte bara säga att jag kan bekräfta problemet

**Comment by stefansundin** [comment]
Hej. Släpper ny version inom kort som fixar UR och NRK.

**Comment by stefansundin** [comment]
Nu är v0.3.7 släppt och det ska fungera igen. Det kan ta ett tag innan uppdateringen godkänns för Chrome, men det är redan ute till Firefox.
