### ISSUE TITLE
Denna går inte att ladda ned helt, bara första 38 sekunderna. Tecken på kommande ändring av videokod? 

### ISSUE THREAD

**Issue by 68456gjp49586g** [stefansundin/privatkopiera#107]
[](https://www.svtplay.se/video/10866877/alla-helgons-blodiga-natt?id=KDZBW3n)

**Comment by stefansundin** [comment]
Hej. Nu var jag lite för sen, verkar som att videon du länkat inte är tillgänglig längre. Andra klipp verkar fungerar dock.
