### ISSUE TITLE
Ännu en film som inte går att ladda ned: Conversion failed!

### ISSUE THREAD

**Issue by 68456gjp49586g** [stefansundin/privatkopiera#108]
https://www.svtplay.se/video/33160938/l-a-konfidentiellt

**Comment by stefansundin** [comment]
Hej. Tyvärr så verkar det som att det är nåt kopieringsskydd på vissa filmer. Har inte ett eget behov att titta närmare på det men om någon annan har lust att hitta ett sätt så godtar jag eventuella fixar.
