### ISSUE TITLE
UR play fungerar inte längre

### ISSUE THREAD

**Issue by Mollupolly** [stefansundin/privatkopiera#109]
Inget verkar att gå att ladda ner från UR längre. Står bara laddar i fönstret. Chrome Version 96.0.4664.45 (Officiell version) (64 bitar)

Ex https://urplay.se/program/217533?source=kunskapskanalen.se&utm_medium=referral

**Comment by Tigerfluga** [comment]
Jag har exakt samma problem. Det står bara att den laddar men inget händer.

**Comment by Sturarna** [comment]
Kan endast bekräfta ovanstående, samma problem här tyvärr.

**Comment by Mollupolly** [comment]
svtplay-dl fungerar men det är lite omständligare https://svtplay-dl.se/

**Comment by toesterdahl** [comment]
Har också uppmärksammat problemet. Tack. Använder Firefox UR-Länk: https://urplay.se/serie/224889-alors-grammaire

**Comment by Guragnidarn** [comment]
Samma problem här (Win 10, Firefox 95.0.2 (64-bitars). UR play, står bara och tuggar "Laddar, var god vänta...". Däremot fungerar SVT Play klanderfritt. Jag såg i en tidigare diskussion (#61) att samma problem fanns i januari 2021, men det fixades då i nästa programversion, om nu det kan vara någon ledtråd.

**Comment by Maltavius** [comment]
Jag har samma problem, Brave i Linux på länken
https://urplay.se/program/207316-bokstavshissen-a
![image](https://user-images.githubusercontent.com/10133945/149615774-50bcf531-0bfe-4ce3-93bc-6f322ebbbb9d.png)

**Comment by stefansundin** [comment]
Hej. Släpper ny version inom kort som fixar UR och NRK.

**Comment by stefansundin** [comment]
Nu är v0.3.7 släppt och det ska fungera igen. Det kan ta ett tag innan uppdateringen godkänns för Chrome, men det är redan ute till Firefox.
