### ISSUE TITLE
Nya behörigheter

### ISSUE THREAD

**Issue by snuggeman** [stefansundin/privatkopiera#11]
Vid uppdatering till 0.1.7 vill pluginen ha
"Åtkomst till dina data för playback-api.b17g.net"

Låter lite skumt utan mer detaljer. Kanske borde kommenteras på hemsidan?

![bild](https://user-images.githubusercontent.com/26237810/41549299-ab1a4554-7325-11e8-85f9-a523b01c30a9.png)

**Comment by Bub0** [comment]
Det är Tv4play. Tillägget får strömmen via den apin :-)

Den mån 18 juni 2018 18:30Magnus Stenman <notifications@github.com> skrev:

**Comment by snuggeman** [comment]
Meddelandet antyder ju att APIt får tillgång till mitt data (vilket data? min profil? mina kontakter?). Därav undran.

**Comment by Bub0** [comment]
Nja jag skulle säga att det står så eftersom tillägget går igenom vilket program du är inne på (din data, alltså öppen flik) för att kunna fråga apin om strömmen men mer insatt än så är jag inte..

**Comment by stefansundin** [comment]
Om du har cookies och liknande på den domänen så kan tillägget nog läsa dem (något som jag inte gör). Tillägget måste också ha behörigheterna för att kunna skicka HTTP-anrop till domänen, något som däremot görs.

TV4Play flyttade deras API från prima.tv4play.se till playback-api.b17g.net, så jag var tvungen att göra detsamma.

Här kan du se ändringarna i koden mellan v0.1.6 och v0.1.7: https://github.com/stefansundin/privatkopiera/compare/v0.1.6...v0.1.7

I någon framtida version så kommer jag nog begära behörigheterna allt eftersom du använder olika tjänster ([optional_permissions](https://developer.chrome.com/extensions/permissions)). Firefox har lite dåligt stöd för detta, vilket är varför jag inte använder det än, men jag tror att de har löst de flesta problemen i kommande versioner.

Med optional_permissions behöver alltså tillägget inte några behörigheter när du installerar det, men om du försöker använda det på tv4play så kan den alltså fråga efter nödvändiga behörigheter. Dock vet jag inte om det kommer se mindre skumt ut eller ej.

**Comment by stefansundin** [comment]
Jag har nu släppt v0.2.0 och det använder `optional_permissions`. (Nya versionen är inte godkänd för Chrome än)

Commits: https://github.com/stefansundin/privatkopiera/commit/1cfdae69859eeec5e7eeb2c09929501b8c760615 och https://github.com/stefansundin/privatkopiera/commit/1862cd73e9d2cbc5324479d62225b5361d1fa44c.

Det visade sig också att jag inte behövde tillgång till de flesta av domänerna som jag begärde. De flesta av dem använder CORS som gör att jag inte behöver begära behörigheter till dem.

Före:

![Screen Shot 2020-06-05 at 5 13 49 PM](https://user-images.githubusercontent.com/1991151/83932167-927dd400-a755-11ea-81de-28bd75f44a2a.png)

Efter:

![Screen Shot 2020-06-05 at 5 13 57 PM](https://user-images.githubusercontent.com/1991151/83932169-97428800-a755-11ea-9cf6-fb8aec13177a.png)

nrk.no använder dock inte CORS (åtminstone inte från alla källor), så där möts man av följande: (https://tv.nrk.no/serie/ardna-tv/2016/SAPP67004716)

![Screen Shot 2020-06-05 at 5 57 52 PM](https://user-images.githubusercontent.com/1991151/83932236-2485dc80-a756-11ea-8d45-5972424439fa.png)

Klickar man på "Bevilja behörigheter" så får man följande fråga:

![Screen Shot 2020-06-05 at 5 58 05 PM](https://user-images.githubusercontent.com/1991151/83932242-2ea7db00-a756-11ea-9c26-a81ec13c7d56.png)

Beviljar man det så måste man öppna Privatkopiera igen och då fungerar det som vanligt:

![Screen Shot 2020-06-05 at 5 59 34 PM](https://user-images.githubusercontent.com/1991151/83932275-55661180-a756-11ea-9364-5c588cf10156.png)

Värt att nämna är att i Firefox så krävs detta även för sverigesradio. I Chrome så ger `activeTab` även behörigheter att kommunicera med domänen på sidan som man öppnat Privatkopiera på. I Firefox så fungerar det inte på samma sätt, så man måste bevilja behörigheter.

På sverigesradio så måste man även bevilja behörigheter så att tillägget kan starta nedladdningen. Detta fungerar bara för ljudfiler (precis som förut).
