### ISSUE TITLE
NRK slutat fungera

### ISSUE THREAD

**Issue by smartinf** [stefansundin/privatkopiera#110]
Se t ex 
https://tv.nrk.no/serie/langrenn/202111/MSPO40291021/avspiller
Skidtävling som är "tillatt for alle" dvs kan ses även i Sverige

Nedladdningar fungerade tidigare (fram till c:a en vecka sedan)

smartinf

**Comment by stefansundin** [comment]
Hej. Släpper ny version inom kort som fixar UR och NRK.

**Comment by stefansundin** [comment]
Nu är v0.3.7 släppt och det ska fungera igen. Det kan ta ett tag innan uppdateringen godkänns för Chrome, men det är redan ute till Firefox.
