### ISSUE TITLE
Svt film funkar ej - "Error parsing ADTS frame header!" 

### ISSUE THREAD

**Issue by Rockyjohan** [stefansundin/privatkopiera#111]
Får bara ner 1.36 av filmen.

"Error parsing ADTS frame header!
[mp4 @ 0x7ff172063000] Error applying bitstream filters to an output packet for stream #1: Invalid data found when processing input
av_interleaved_write_frame(): Invalid data found when processing input"

https://www.svtplay.se/video/33342606/manchester-by-the-sea

**Comment by stefansundin** [comment]
Hej. Tyvärr så verkar det som att det är nåt kopieringsskydd på vissa filmer (speciellt Amerikanska filmer). Har inte ett eget behov att titta närmare på det men om någon annan har lust att hitta ett sätt så godtar jag eventuella fixar.
