### ISSUE TITLE
hej jag har problem att ladda ner en video från tv4 play.

### ISSUE THREAD

**Issue by Visseb** [stefansundin/privatkopiera#112]
**hej jag har problem att ladda ner en video från tv4 play.
jag har enbart lagt ffmpeg på skrivbordet, men får detta error när jag försöker få ett kommando från sidan.**

**API säger "<html><body>

errorCode | "asset_not_found"
-- | --
message | "TV4 asset not found"
details | "{ data: { videoAsset: null } }"

</body>
</html>
**

https://www.tv4play.se/program/lysande-j%C3%B6nssonligan-40-%C3%A5r

![ddddd](https://user-images.githubusercontent.com/96743841/147496940-67cf7000-3b3c-4865-8c72-15bf1443a985.png)

**Comment by stefansundin** [comment]
Hej. Tyvärr fungerar inte Privatkopiera på filmer från TV4. :(

**Comment by Visseb** [comment]
Tjena! Jag fick fart på det, det var jag som inte hade rätt sida framme för video spelaren på hemsidan så jo det gick för mig 😀

Hämta Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BacchusFLT** [comment]
Stefan: svtplay-dl har en funktion för att extrahera token och sedan skall det funka med TV4 play. Jag får förstås det inte att fungera, men i princip borde Privatkopiera också kunna plocka fram token och använd den för att ladda ner från denna källa?

**Comment by stefansundin** [comment]
Hej @BacchusFLT. Det här är en gammal tråd som jag har glömt bort. Det här fungerar nu i Privatkopiera. Tack för påminnelsen.
