### ISSUE TITLE
"I hetast laget"

### ISSUE THREAD

**Issue by LLindfors61** [stefansundin/privatkopiera#118]
Hej!

För övriga program testade på SVT Play verkar programmet fungera finfint, men har problem med en av mina favoritfilmer, "I hetaste laget", finns här https://www.svtplay.se/video/29402516/i-hetaste-laget?id=jx1Yp2D. Bifogar också vad som händer i Terminal (macOS). Har använt ffmpeg (ffmpeg-106438-g23cb87bb3c), såvitt jag förstår den senaste versionen.

Hoppas du kan åtgärda problemet - gillar verkligen filmen...

Med Vänlig Hälsning 

Lennar
[Privatkopiera.pdf](https://github.com/stefansundin/privatkopiera/files/8355382/Privatkopiera.pdf)
t

**Comment by stefansundin** [comment]
Hej Lennart,

Kan du testa ta bort `-acodec copy`? Jag tror att det har något med ljudströmmen att göra, om jag förstår felmeddelandet rätt. Utan `-acodec copy` så ska FFmpeg koda om ljudströmmen och förhoppningsvis fungerar det bättre då.

Det är en gissning men förhoppningsvis hjälper det.

**Comment by LLindfors61** [comment]
Hej!

Detta fungerar för video-signalen men inget ljud. I början får jag samma felmeddelande angående ffmpeg-version.

Med Vänlig Hälsning 

Lennart

26 mars 2022 kl. 21:50 skrev Stefan Sundin ***@***.***>:


Hej Lennart,

Kan du testa ta bort -acodec copy? Jag tror att det har något med ljudströmmen att göra, om jag förstår felmeddelandet rätt. Utan -acodec copy så ska FFmpeg koda om ljudströmmen och förhoppningsvis fungerar det bättre då.

Det är en gissning men förhoppningsvis hjälper det.

**Comment by Lunarwalker60** [comment]
Hej på er!

Jag kör i Windows 7 Pro med ffmpeg v 4.22 och det fungerar alltid. Det finns tydligen en build 5.0 men jag har inte haft anledning att uppdatera än.

Se bifogade screenshots.
![ffmpeg-422](https://user-images.githubusercontent.com/61702762/160266242-78f83e30-120c-42cc-bfdc-a2c9ab467c5f.JPG)
![I hetaste laget - Log](https://user-images.githubusercontent.com/61702762/160266247-d6a1c55b-6498-4aa8-aaf0-3b673acee785.JPG)
![I hetaste laget - PCopy](https://user-images.githubusercontent.com/61702762/160266251-06a4cb6c-f111-4948-8dc0-d07ac86ff023.JPG)

Lycka till!
/S

**Comment by LLindfors61** [comment]
Hej!

Tack för alla tips (och tillägget) men sitter med en Mac och får exakt samma results som nämns på https://github.com/stefansundin/privatkopiera/discussions/57 <https://github.com/stefansundin/privatkopiera/discussions/57>, dvs film med ca 3 min ljud och resten tyst. Och kan inte hitta något senare FFmpeg än det jag använder…

Med Vänlig Hälsning 

Lennart

27 mars 2022 kl. 06:10 skrev Lunarwalker60 ***@***.***>:


Hej på er!

Jag kör i Windows 7 Pro med ffmpeg v 4.22 och det fungerar alltid. Det finns tydligen en build 5.0 men jag har inte haft anledning att uppdatera än.

Se bifogade screenshots.
 <https://user-images.githubusercontent.com/61702762/160266242-78f83e30-120c-42cc-bfdc-a2c9ab467c5f.JPG>
 <https://user-images.githubusercontent.com/61702762/160266247-d6a1c55b-6498-4aa8-aaf0-3b673acee785.JPG>
 <https://user-images.githubusercontent.com/61702762/160266251-06a4cb6c-f111-4948-8dc0-d07ac86ff023.JPG>
Lycka till!
/S
