### ISSUE TITLE
Ström-länk

### ISSUE THREAD

**Issue by huggla** [stefansundin/privatkopiera#12]
Skulle ni kunna ordna ett fält med endast urlen till videoströmmen? Jag vill använda den i andra program och vill slippa att varje gång behöva klippa och klistra från ffmpeg-kommandot.

**Comment by stefansundin** [comment]
Fixat i https://github.com/stefansundin/privatkopiera/commit/875ba1bf3acb4d5bdd14debc81e03772dd12626f (v0.1.8). Håll ner shift när du klickar på knappen så kopieras endast URLen. Öppna gärna igen om du kommer på nåt som kan förbättras.
