### ISSUE TITLE
Problem att ladda från URplay

### ISSUE THREAD

**Issue by Guragnidarn** [stefansundin/privatkopiera#121]
Kan inte ladda från URplay. Har försökt med Firefox och Chrome, cmd.exe skriver ett 40-tal rader och avslutar med "Permission denied" i röd text. Samma vid flera olika försök med olika UR-program, nu senast "Motströms på Donau".
![UPplay](https://user-images.githubusercontent.com/97201186/162780078-dfcf60b2-1572-463c-928f-5aa01ea25ce4.JPG)

**Comment by stefansundin** [comment]
Hej! Problemet här är inte UR eller Privatkopiera. Du försöker skriva filen till en mapp som du inte har behörigheter till.

Du missade den här varningen på hemsidan:

> **Obs:** Kör inte kommandon från `C:\` (eller `C:\Windows\`). I nya versioner av Windows så kan inte vanliga användare skriva här. Jag rekommenderar att du kör kommandon från ditt skrivbord. För att navigera till skrivbordet, skriv först "`cd Skrivbord`".

I ditt fall måste du nog skriva `cd C:\Users\dittanvandarnamn\Skrivbord` eller nåt liknande.

Hoppas det hjälper!

**Comment by Guragnidarn** [comment]
Hej och hjärtligt tack för hjälpen, dina råd till en novis hjälpte!
Själv hade jag inte en tanke på att felet låg där. Nu fungerar det klanderfritt.
Än en gång tack!!
mvh
Bengt-Åke
________________________________
Från: Stefan Sundin ***@***.***>
Skickat: den 11 april 2022 19:47
Till: stefansundin/privatkopiera ***@***.***>
Kopia: Guragnidarn ***@***.***>; Author ***@***.***>
Ämne: Re: [stefansundin/privatkopiera] Problem att ladda från URplay (Issue #121)


Hej! Problemet här är inte UR eller Privatkopiera. Du försöker skriva filen till en mapp som du inte har behörigheter till.

Du missade den här varningen på hemsidan:

Obs: Kör inte kommandon från C:\ (eller C:\Windows\). I nya versioner av Windows så kan inte vanliga användare skriva här. Jag rekommenderar att du kör kommandon från ditt skrivbord. För att navigera till skrivbordet, skriv först "cd Skrivbord".

I ditt fall måste du nog skriva cd C:\Users\dittanvandarnamn\Skrivbord eller nåt liknande.

Hoppas det hjälper!
