### ISSUE TITLE
Problem med TV4 Play fr.o.m. den 20/4

### ISSUE THREAD

**Issue by H2SO4JB** [stefansundin/privatkopiera#122]
Hej Stefan,

Från och med igår den 20/4 så har jag problem med att ladda ner vissa program från TV4 Play med ditt tillägg. Jag brukar exempelvis ladda ner "Robinson - Gränslandet" varje dag när det släpps, men nu helt plötsligt så svarar ditt tillägg med följande felkod:
"Fel: API svarade med kod 404."
Exempel: `https://www.tv4play.se/program/robinson/robinson-gr%C3%A4nslandet-del-1-s%C3%A4song-2022/13742797?playlist=92d2c990-a68d-11ec-9e58-b1d8c6b744bc`

Jag har även märkt att jag helt plötsligt måste vara inloggad för att se programmet men det hjälper inte för själva nedladdningen så TV4 verkar ha ändrat något.

Vissa program fungerar dock fortfarande, exempelvis detta:
`https://www.tv4play.se/program/wonderland/del-1-weddings-s%C3%A4song-1/13343210`

Kan du svara på vad detta beror på och om det går att fixa? Tack på förhand.

**Comment by PeterWaldero** [comment]
...jag har noterat exakt samma fel.

**Comment by Myrmicat** [comment]
Jag har samma problem. Kunde ladda ner en del av Sisi för några dagar sen, men får nu detta fel.

**Comment by snovind55** [comment]
Hej!
Sparat två "Hamilton" filmer från tv4play den ena ok och den andra ej fullständig eller spelbar och med "Failed to seek for auxiliary info, will only parse senc atoms for encryption info" som respons på varje rad.
("Men inte om det gäller min dotter" = felar   "I nationens intresse" = ok)
Någon som känner igen? Åtgärd?

**Comment by H2SO4JB** [comment]
Eftersom man inte får någon som helst respons här så stänger jag härmed detta ärende.

**Comment by stefansundin** [comment]
Det här är kanske fixat i v0.3.8. Fixade ett problem med tv4.se som förmodligen fixade lite grejor på tv4play.se men jag har ingen möjlighet att testa.

**Comment by H2SO4JB** [comment]
Fungerar för mig nu. Tack som fan! 👍🏻

**Comment by PeterWaldero** [comment]
Ja, den tv-episod som jag provade att ladda ner tycks funka bra.
Så, man tackar.
Jag ska se om jag kan skicka iväg en liten peng som tack, jag har haft ett
flertal stora oförutsedda utgifter nyligen, men några kronor bör jag kunna
avvara.

mvh Uffe

**Comment by H2SO4JB** [comment]
Jag donerade precis $10, det är alltid något som tack för ditt jobb. 👍🏻
