### ISSUE TITLE
SVT Min Onkel Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by MS-CDAB** [stefansundin/privatkopiera#123]
Jag får detta fel bara för denna film (hittills). (Laddar ner Semestersabotören just nu vilket verkar gå fint.)

<img width="830" alt="image" src="https://user-images.githubusercontent.com/46790341/168553125-17d64676-9136-4ab2-b093-4167d3e4b283.png">

**Comment by Lunarwalker60** [comment]
Programmet publiceras inte förrän 20/5 - försök igen då.

/S

**Comment by stefansundin** [comment]
I den senaste versionen (v0.3.8) så visas ett bättre felmeddelande i detta fallet.
