### ISSUE TITLE
tv.nrk.no

### ISSUE THREAD

**Issue by gthing313** [stefansundin/privatkopiera#124]
Provar ladda ner fil från tv.nrk.no men får: Fel: [API](https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MUHH41000121&property=HlsUrl&useragent=Mozilla%2f5.0) svarade med kod [404](https://httpstatuses.com/404).

URL till avsnitt: https://tv.nrk.no/serie/foerstegangstjenesten/sesong/2/episode/1/avspiller

**Comment by olekang** [comment]
NRK har endret oppsettet sitt en del. Så man må finne video_id og linker til m3u8 listene på en annen måte.
Se #129 for hva jeg gjorde for å få delene jeg trengte til å virke.

**Comment by stefansundin** [comment]
Hej. Har precis släppt v0.3.10 som fixar problemen med nrk.no och dr.dk.
