### ISSUE TITLE
dr.dk og tv.nrk.no

### ISSUE THREAD

**Issue by sketch3** [stefansundin/privatkopiera#126]
"Error: Failed to fetch"
Eks.: https://www.dr.dk/drtv/se/de-blodroede-floder_-den-sidste-jagt_321501

tv.nrk.no/
Stadig fejl: "Fel: API svarade med kod 404."
Eks.: https://tv.nrk.no/serie/dagsrevyen/202207/NNFA19072122/avspiller

**Comment by smartinf** [comment]
Testade följande sida (rullskidstävling):
https://tv.nrk.no/serie/skishow-paa-sommerfoere/2022/MSPO40380522/avspiller
Privatkopiera gav följande kod:
ffmpeg -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSPO40380522&property=HlsUrl&useragent=Mozilla%2f5.0" -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSPO40380522&property=WebVttSubtitles&useragent=Mozilla/5.0" -vcodec copy -acodec copy "Skiskyting og langrenn.mkv"

Fast fungerar inte. Felmeddelande:
Server returned 404 Not Found

**Comment by stefansundin** [comment]
Hej. Har precis släppt v0.3.10 som fixar problemen med nrk.no och dr.dk.
