### ISSUE TITLE
urplay.se fungerar ej

### ISSUE THREAD

**Issue by larsnystrom** [stefansundin/privatkopiera#127]
Försöker ladda ner denna ström: https://urplay.se/program/202840-smasagor-piraterna-och-regnbagsskatten

Har även försökt andra strömmar men samma fel där.

I Firefox står det "Error: stream is undefined" och i Chrome står det "Error: Cannot read properties of undefined (reading 'getAttribute')".

Har version 0.3.7 av Privatkopiera.

**Comment by stefansundin** [comment]
Det här ska nu vara fixat i v0.3.8. Förlåt att det dröjde. Läs mer här: https://github.com/stefansundin/privatkopiera/discussions/142
