### ISSUE TITLE
SVT Play

### ISSUE THREAD

**Issue by sketch3** [stefansundin/privatkopiera#132]
Bat-filen med relevant kommando starter ikke. Tunna blå linjen afsnit 1 og 2 kunne hentes, men ikke længere. Det ser ud til at gælde alt på SVT Play
Eks.: https://www.svtplay.se/video/36884843/tunna-bla-linjen/tunna-bla-linjen-sasong-2-avsnitt-3?id=K5RLpGa

NRK TV  og DRTV virker heller ikke.

**Comment by sketch3** [comment]
Fejl i bat-fil skyldtes, at Notepad tilføjede nogle usynlige tegn, så ffmpeg blev til ï»¿ffmpeg, som kan ses og fjernes i UltraEdit. Nu virker bat-fil i SVT Play. Savner stadig en løsning til NRK TV og DRTV.

**Comment by Kvandalma** [comment]
Hej! Jag vet inte om vi har samma problem, men när jag försöker ladda ned en film från SVT Play blir jag bara meddelad om att hemsidan inte stöds. Vet någon vad som pågår?
