### ISSUE TITLE
SVTPlay problem

### ISSUE THREAD

**Issue by granitsten** [stefansundin/privatkopiera#133]
Flertalet filmer samt vissa andra program t.ex dokumentärer startar ej, antingen får man ett "Var god vänta"-meddelande eller att sidan ej stöds. Här är exempel på en film som meddelar att sidan ej stöds
https://www.svtplay.se/video/KPv5PLo/landstormens-lilla-argbigga

**Comment by mekew** [comment]
Upplever samma problem. Märkligt nog verkar problemet dock vara beroende av vilken sida man går till en film ifrån. Om man klickar på filmer från SVTPlays kategori "UPPTÄCK" (här: https://www.svtplay.se/kategori/filmer), så kan vissa av titlarna fungera. Om man går från den fulla listan, i bokstavsordning ("PROGRAM A-Ö"), fungerar inte någon av titlarna.

**Comment by mekew** [comment]
Jag gjorde en extra koll på SVTplay nu. Det verkar som att de har någon ny slags sortering för filmerna, som inte är implementerad överallt. Till exempel: när man går till filmen "You Were Never Really Here" från kategorin "UPPTÄCK" (nämnd ovan), blir url:en: https://www.svtplay.se/video/26987573/you-were-never-really-here Privatkopiera fungerar på den sidan. Men om man går till filmen via "PROGRAM A-Ö" blir url:en: https://www.svtplay.se/video/jMdpXq6/you-were-never-really-here

**Comment by wisechimp** [comment]
Sorry to join the discussion in English, but have SVT changed the format of the url recently? The examples that seem to work have an integer in the url after "www.svtplay.se/videos/" while the ones that don't have a string instead. I note that one of the matchers in svt.js (line 105) takes an int (legacyId) and fetches a "SvtId", which is a string in a similar structure to the string in the non-functioning SVT url after "www.svtplay.se/videos/".

As an example I found the following url for England - Iran (woo hoo!):

https://www.svtplay.se/video/37410089/fifa-fotbolls-vm-2022/fifa-fotbolls-vm-2022-england-iran-21-nov-13-30

and Privatkopiera is happy with this. If I take the 37410089 and plug it into the api in the above matcher I get an SvtId of KXA4nE6. This url works:

https://www.svtplay.se/video/KXA4nE6/fifa-fotbolls-vm-2022/fifa-fotbolls-vm-2022-england-iran-21-nov-13-30

although Privatkopiera doesn't recognise it, but KXA4nE6 seems to give a response if I enter it into the api calls in svt.js.

**Comment by mekew** [comment]
> Sorry to join the discussion in English, but have SVT changed the format of the url recently? The examples that seem to work have an integer in the url after "www.svtplay.se/videos/" while the ones that don't have a string instead. I note that one of the matchers in svt.js (line 105) takes an int (legacyId) and fetches a "SvtId", which is a string in a similar structure to the string in the non-functioning SVT url after "www.svtplay.se/videos/".
> 
> As an example I found the following url for England - Iran (woo hoo!):
> 
> https://www.svtplay.se/video/37410089/fifa-fotbolls-vm-2022/fifa-fotbolls-vm-2022-england-iran-21-nov-13-30
> 
> and Privatkopiera is happy with this. If I take the 37410089 and plug it into the api in the above matcher I get an SvtId of KXA4nE6. This url works:
> 
> https://www.svtplay.se/video/KXA4nE6/fifa-fotbolls-vm-2022/fifa-fotbolls-vm-2022-england-iran-21-nov-13-30
> 
> although Privatkopiera doesn't recognise it, but KXA4nE6 seems to give a response if I enter it into the api calls in svt.js.

Yes, this is exactly it! You obviously know more about coding than me, but this is what seems to be the problem, which I wrote about in Swedish above. SVTplay has implemented some kind of new system. I've recognized one place where you can reach their feature length films with old URLs, but mostly, the new ones have been implemented everywhere, and Privatkopiera can't recognize the files as a result.

**Comment by Rockyjohan** [comment]
Yo! Allmighty @stefansundin ! Save us!

**Comment by Ordval** [comment]
Jag repeterar min kommentar på [Problem med nedladdning av film från SVT Play #135](https://github.com/stefansundin/privatkopiera/discussions/135) 
här:
"[svtplay-dl ](https://svtplay-dl.se/archive/) är absolut en möjlighet, 
nu använder jag bara den (och Privatkopiera) för att få 
tag i MRL:erna `svtplay-dl --get-only-episode-url`  
(så vad gäller resten vet jag inte)."

[DuckRandom](https://github.com/DuckRandom) tipsar också om att använda "yt-dlp",  
båda krångligare förstås men i mellantiden en möjlighet. 

I repeat my comment on [Problem med nedladdning av film från SVT Play #135](https://github.com/stefansundin/privatkopiera/discussions/135)
here:
"[svtplay-dl ](https://svtplay-dl.se/archive/) is definitely a possibility,
now, I just use it (and Privatkopiera) to get
the MRLs `svtplay-dl --get-only-episode-url`
(so as for the rest I don't know)."

[DuckRandom](https://github.com/DuckRandom) also suggests using "yt-dlp",
both of them more complicated of course but 
in the meantime a possibility.

**Comment by stefansundin** [comment]
Det här ska nu vara fixat i v0.3.8. Förlåt att det dröjde. Läs mer här: https://github.com/stefansundin/privatkopiera/discussions/142



> Men om man går till filmen via "PROGRAM A-Ö" blir url:en: https://www.svtplay.se/video/jMdpXq6/you-were-never-really-here

Tyvärr så måste du nu klicka play på videon så att URL:en blir följande: https://www.svtplay.se/video/Kv19Vwg/you-were-never-really-here?id=Kv19Vwg

Jag kanske ska kräva att det finns en `id=` parameter istället för att plocka ut ID:et från `/Kv19Vwg/`.
