### ISSUE TITLE
TV4 slutat fungera

### ISSUE THREAD

**Issue by Ahgitten** [stefansundin/privatkopiera#138]
T.ex. https://www.tv4play.se/program/bachelor-sverige?tab=episodes 
eller
https://www.tv4play.se/program/bonde-s%C3%B6ker-fru?tab=episodes
så det gäller nog allmänt hela tv4.
![bild](https://user-images.githubusercontent.com/118282384/201939349-9f1052f3-f3a1-48d5-adf5-ab5ac35338f2.png)

SVT fungerar utmärkt fortfarande dock.

**Comment by johnwildcat** [comment]
Någon som vet vad det är för fel?
Det har funkat klockrent fram tills igår (2022-11-14) sen får jag bara upp detta felmeddelande.
![FEL_TV4PLAY](https://user-images.githubusercontent.com/118253846/202028328-65017d17-0fc1-431a-b46b-a494d17f7db5.jpg)


Svtplay funkar fortfarande dock.

**Comment by Lunarwalker60** [comment]
Jag har kollat lite på det och TV4 har definitivt ändrat upplägget på sina program. Hittade manifesten manuellt men kan inte hitta tråden som man behöver för att nysta upp och bygga ett nerladdningskommando automatiskt. Stefan kanske kan fixa det när han får tid.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2022-11-15, 22:24 johnwildcat ***@***.***> wrote:

   
  Någon som vet vad det är för fel? Det har funkat klockrent fram tills igår (2022-11-14) sen får jag bara upp detta felmeddelande.  
  Svtplay funkar fortfarande dock.

**Comment by johnwildcat** [comment]
Tack för snabbt svar!
Hojta till så fort ni vet något mer. :)
Tack på förhand! Schysst!

**Comment by mekew** [comment]
SVT fungerar **inte** utmärkt för flera av oss fortfarande!! Se några posts under detta inlägg.

**Comment by Ahgitten** [comment]
> SVTPlay fungerar **inte** för flera av oss fortfarande!! Se några posts under detta inlägg.

Ok.. jag kör Firefox (av någon märklig anledning finns inte tillägget till Opera så man måste köra slöa Firefox i stället) och kollade alldeles nyss och den här fungerar i alla fall: https://www.svtplay.se/video/36225209/svenska-nyheter/svenska-nyheter-sasong-10-28-okt-22-00?info=visa

**Comment by mekew** [comment]
> > SVTPlay fungerar **inte** för flera av oss fortfarande!! Se några posts under detta inlägg.
> 
> Ok.. jag kör Firefox (av någon märklig anledning finns inte tillägget till Opera så man måste köra slöa Firefox i stället) och kollade alldeles nyss och den här fungerar i alla fall: https://www.svtplay.se/video/36225209/svenska-nyheter/svenska-nyheter-sasong-10-28-okt-22-00?info=visa

Ah, ok! Jag kör Google Chrome. SVTplay verkar ha börjat implementera ett nytt system för att sortera sina filmer och klipp, och jag får intrycket att tillägget därför inte kan identifiera filerna, beroende på vilken av SVTplays undersidor man befinner sig på. Skrev mer om det (med exempel) i den andra tråden.

**Comment by stefansundin** [comment]
Det här är troligen fixat i v0.3.8. Jag kan inte testa tv4play.se men tv4.se fungerar nu igen. Jag tror de har samma backend. Öppna gärna den här igen om det visar sig att det fortfarande är trasigt.

**Comment by H2SO4JB** [comment]
Fungerar för mig nu. Tack som fan! 👍🏻

**Comment by johnwildcat** [comment]
> 

Stort tack!
Nu funkar det för mej också. Jag behöver inte installera om någonting utan funkade bara köra på som vanligt!
Tv4 play funkar klockrent.
