### ISSUE TITLE
SVT fungerar inte

### ISSUE THREAD

**Issue by kjxerox** [stefansundin/privatkopiera#139]
Även SVT har slutat fungera. Följande meddelande visas: 
Fel: Den här hemsidan stöds ej.

**Comment by mekew** [comment]
Kolla trådarna härunder. Några av oss har elaborerat mer där.

**Comment by stefansundin** [comment]
Det här ska nu vara fixat i v0.3.8. Förlåt att det dröjde. Läs mer här: https://github.com/stefansundin/privatkopiera/discussions/142
