### ISSUE TITLE
Privatkopiera v0.3.8. - SVTPlay

### ISSUE THREAD

**Issue by mekew** [stefansundin/privatkopiera#143]
Tillägget i Chrome har nu uppdaterats till v0.3.8., men det verkar fortfarande inte gå att ladda ned filmer på SVTPlay. Tillägget kallar felet: "Error to fetch." Man ser att tillägget vill spara filen med samma bokstäver och siffror som i url:en för respektive film. Detta gäller t ex alla filmer på SVTPlays filmsida, A-Ö: https://www.svtplay.se/kategori/filmer?tab=all (OBS: jag kan inget om kodning, så det är endast detta jag kan rapportera.)

OBS2: jag använder senaste versionen av Google Chrome som är "Version 107.0.5304.121 (Officiell version) (x86_64)".

**Comment by mekew** [comment]
Såg nu att det kommit ett svar från Stefan medelst mail, som jag inte kunde se här på gitHub. Allt verkar funka, med den enda skillnaden att man nu måste trycka på "play"/starta filmen innan man får fram länken!

**Comment by henrik2h** [comment]
Jag får inte fram någon ström/länk oavsett om filmen spelar eller är pausad. Testat både i Chrome och Edge. Bara Error to fetch..

**Comment by henrik2h** [comment]
Spelar jag filmen så kommer strömmen inte upp även om jag väntar. Går jag in på inställningarna, backar tillbaka, trycker "spela" igen på filmen så kommer strömmen upp.

**Comment by RogerGustavsson** [comment]
Får inte längre med undertext från svtplay. Har något ändrat på sistone? Kanske i Chrome?
