### ISSUE TITLE
Tv.nrk.no är problem!

### ISSUE THREAD

**Issue by jonas9881** [stefansundin/privatkopiera#148]
Jag har försökt ladda ner denna och först så fick jag typ acceptera att det tillägget fick ladda ner från den websidan ochs edan så testade jag och valde avsnitt 1 av "Julekongen" och då fick jag koden:

ffmpeg -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSUS24000112&property=HlsUrl&useragent=Mozilla%2f5.0" -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSUS24000112&property=WebVttSubtitles&useragent=Mozilla/5.0" -vcodec copy -acodec copy "Julekongen.mkv"

men den funkar inte och jag testade att hitta undertexten men finner den inte heller!

Vet någon vad detta problem uppstår på grund av?  Vet någon lösningen?

För jag vet inte alls hur jag ska ta till väga, jag testade även att lägga till ".m3u8" efter "5.0" som till exempel detta:

ffmpeg -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSUS24000112&property=HlsUrl&useragent=Mozilla%2f5.0.m3u8" -i "https://psapi.nrk.no/obsoleteproperty?endpoint=programs/MSUS24000112&property=WebVttSubtitles&useragent=Mozilla/5.0.m3u8" -vcodec copy -acodec copy "Julekongen.mkv"

men det verkar inte heller funka, kan någon hjälpa mig, för det står att det ska gå att ladda ner och funka här: https://stefansundin.github.io/privatkopiera/

Här är serien: https://tv.nrk.no/serie/julekongen/sesong/1/episode/1/avspiller

**Comment by subhappy** [comment]
Bekrefter at det er et problem.
Privatkopiera sier: "Fel: [API](https://psapi.nrk.no/obsoleteproperty?endpoint=programs/KOIF75000319&property=HlsUrl&useragent=Mozilla%2f5.0) svarade med kod [404](https://httpstatuses.com/404)."

Om man går inn på API får man meldingen {"message":"Your app is trying to access the content from an incorrect endpoint!"}

**Comment by jonas9881** [comment]
Korrekt men om du går in på "inspect" eller trycker på ctrl + shift + i så väljer du sen "network" och sedan uppdaterar sidan och då letar du upp först undertexten som du hittar när du söker på "vtt" och sedan filmen hittar du när du säker på "m3u8" och välj rätt länk och använd cmd-programmet för att ladda ner det. DETTA ÄR FACIT TILL HEMSIDAN :)

**Comment by oomberg** [comment]
> Korrekt men om du går in på "inspect" eller trycker på ctrl + shift + i så väljer du sen "network" och sedan uppdaterar sidan och då letar du upp först undertexten som du hittar när du söker på "vtt" och sedan filmen hittar du när du säker på "m3u8" och välj rätt länk och använd cmd-programmet för att ladda ner det. DETTA ÄR FACIT TILL HEMSIDAN :)


Kan bekräfta att detta funkar idag, 6e april.

**Comment by stefansundin** [comment]
Hej. Har precis släppt v0.3.10 som fixar problemen med nrk.no och dr.dk.
