### ISSUE TITLE
Om Privatkopiera läggs i `Overflow menu` går den inte att ändra storlek

### ISSUE THREAD

**Issue by Sopor** [stefansundin/privatkopiera#15]
När jag lägger Privatkopiera i `Overflow Menu` så går det inte att göra Privatkopiera-fönstret större än så här:
![image](https://user-images.githubusercontent.com/5789283/43378782-366aa4a0-93c9-11e8-95eb-3bf0e023d024.png)

**Comment by stefansundin** [comment]
Hittade detta: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups

> If the user moves the extension's button to the menu or it appears in the toolbar overflow, then the popup appears inside the menu's panel and is given a fixed width.

Så jag tror att mitt enda val är att på nåt vis detektera om popupen är i overflow menyn, och försöka trycka ihop allt så att det får plats. Tar gärna emot tips hur detta kan göras.

**Comment by Sopor-** [comment]
Det var ju en miss att de gjort så. Tyvärr är jag ingen kodare så jag har inget att komma med. Hoppas nån har nån idé...

**Comment by stefansundin** [comment]
Detta är inte längre ett problem sedan Firefox 106. https://bugzilla.mozilla.org/show_bug.cgi?id=1783972
