### ISSUE TITLE
Error: Failed to fetch - v0.3.8 @ svtplay.se - Fick det att funka igen :D tack för ett awesome tillägg!  

### ISSUE THREAD

**Issue by robbenu** [stefansundin/privatkopiera#155]
https://www.svtplay.se/video/Kv1aLMw/julkalendern-kronprinsen-som-forsvann/avsnitt-1?id=8ZDLRyQ

Får det inte att funka på SVT men på TV4 går det. 
Hjääälp! :D

**Comment by robbenu** [comment]
kör med Chrome, senaste version.

**Comment by jonas9881** [comment]
Vad är problemet, ge gärna ett så utförlig information så vi fattar vad ditt problem är :)

Du måste först spela videon, sedan pause och sedan får du koden om du nu inte ens har spelat upp videon innan du letar upp koden.

**Comment by henrik2h** [comment]
Samma problem här, tillägget hittar inte strömmen, går inte välja något i rullistan. Står som i rubriken här "Error: Failed to fetch". Använt många gånger förut så vet hur man gör.

**Comment by robbenu** [comment]
Fick det att funka efter att ha kört svt i ett eget fönster, dvs inte massa flikar uppe. kanske funkar med att bomba F5 med. men jag har ju en vana att ha minst 256 flikar igång. så testa! (:
