### ISSUE TITLE
Kalle Anka

### ISSUE THREAD

**Issue by textures2** [stefansundin/privatkopiera#156]
Här är länken, klassikern:
https://www.svtplay.se/video/8Wv6LvJ/julvarden-och-kalle-anka?id=ch-svt1

Den kommer tas bort vid midnatt.

Jag försökte lista ut URL:en själv och testade följande "för hand":
ffmpeg -i "https://svt-secure-c.akamaized.net/secure/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v2/v2.m3u8" -vcodec copy -acodec copy "kalleanka.mkv"

Jag får en massa output, ser ut som den försöker spara filen:

```
[hls @ 0x557dfc4af6c0] Opening 'crypto+https://svt-secure-c.akamaized.net/secure/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v2/v2-5539103.mp4?aka_me_session_id=AAAAAAAAAADYZKhjAAAAABls7SAj9jeIEYA52SqU1GEq9+4eS5KKASKfqsZpQErE5nM%2fP2jDPa7YDGpfdi3NX01KaxRPgXpl&aka_msn=5539103&aka_hls_version=6&aka_media_format_type=hls' for reading
[https @ 0x557dfc822a00] Opening 'https://svt-secure-c.akamaized.net/secure/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v2/v2.m3u8' for reading
[hls @ 0x557dfc4af6c0] Skip ('#EXT-X-VERSION:6')
[hls @ 0x557dfc4af6c0] Opening 'https://svt-secure-c.akamaized.net/secure/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v2/v2-init.mp4?aka_me_pasthr=AAAAAAAAAADbZKhjAAAAAKHJ8Zg5AWKgOLmNT2YyBUkJ2H6Np1MNthf52hkEHK1fhU7OsdMVX6S1518JhI4DAoNz2BV9THiw&aka_media_format_type=hls&aka_sign=a8GFnXQ1BCWYQKmtXK4f87Hcqj0zPg6DGBhKdl63j%2bI%3d' for reading
[hls @ 0x557dfc4af6c0] Opening 'https://svt-secure-c.akamaized.net/secure/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v2/serve.key?aka_me_session_id=AAAAAAAAAADbZKhjAAAAAKHJ8Zg5AWKgOLmNT2YyBUkJ2H6Np1MNthf52hkEHK1fhU7OsdMVX6S1518JhI4DAoNz2BV9THiw' for reading
```

Dock är filen helt töm...

God jul!

**Comment by Lunarwalker60** [comment]
Denna funkade som direktinspelning:
ffmpeg -i "https://svt1-c.akamaized.net/se/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-v1/v1.m3u8" -i "https://svt1-c.akamaized.net/se/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-a0/a0.m3u8" -i "https://svt1-c.akamaized.net/se/svt1/5eff9010-33e6-4944-b906-1e885e20d659/dash-s0/s0.m3u8" -t 01:08:30 -c copy "Juldisney 2022.mkv"

**Comment by textures2** [comment]
Testade men sedan upptäckte att länken måste ha blivit fel eller nåt.  Fick fel program.  Filen började med Sagan om Karl-Bertil Jonssons julafton...

Tack för hjälpen i alla fall.

**Comment by Lunarwalker60** [comment]
God morgon! Det beror på att länken jag publicerade är en länk för direktinspelning - man måste vara med och starta ffmpeg när programmet startar. Just Jul-Disney publiceras på SVT Play endast för direkt visning. Se på det som gamla tiders videoinspelning.

Jag har gjort en app för detta:
![SVT-Direkt](https://user-images.githubusercontent.com/61702762/209460541-032adbf3-7a88-4580-a7d0-dc34c327f20b.JPG)

**Comment by textures2** [comment]
Tack för återkopplingen.

Disney-länken var tillgänglig i flera timmar på hemsidan.  Testade att
klicka på den vid flera tillfällen efter 15.00 och den började från början.

Eller så har jag missförstått totalt?

**Comment by Lunarwalker60** [comment]
Länken funkar fortfarande men nu fångar den reprisen av På Spåret - alltså det som visas på Play just nu...
