### ISSUE TITLE
Jag lyckas inte att ladda ned Rapport från SVTPlay

### ISSUE THREAD

**Issue by Daniel333xxx** [stefansundin/privatkopiera#162]
Hej!

I ett par år har jag laddat ned TV-program från SVTPlay. Det har fungerat jättebra fram till nu, men nu går det inte alls. Har installerat om Chrometillägget Privatkopiera, med samma resultat. Har dock inte installerat om FFMPEG. Behöver man göra det? Här är länk till en print screen:

[Rapport 230121 - Privatkopiera.docx](https://github.com/stefansundin/privatkopiera/files/10530912/Rapport.230121.-.Privatkopiera.docx)

![image](https://user-images.githubusercontent.com/81932256/215356464-53e081e4-d1ce-4261-a785-8e87a51e916a.png)

Mvh,
Daniel

**Comment by stefansundin** [comment]
Verkar fungera nu... nästa gång så får du gärna klistra in en länk istället för en skärmdump. Tack!
