### ISSUE TITLE
privatkopiera fungerar ej på svtplay

### ISSUE THREAD

**Issue by pulsro** [stefansundin/privatkopiera#166]
hej
svtplay fungerar ej nu (men gjorde för några dagar sedan). 
Får följande meddelande; 
[tcp @ 00000125745eee40] Connection to tcp://svt-vod-8a.akamaized.net:443 failed: Error number -138 occurred
https://svt-vod-8a.akamaized.net/d0/se/20221226/2bec3b01-7d52-41ca-a9bc-67d42002896b/hls-ts-avc.m3u8: Unknown error
När jag öppnar PK stannar strömmen på t ex: his-ts-avc.m3u8. Den byts inte ut till vad som kom upp tidigare. (om storlek mm)

**Comment by stefansundin** [comment]
Hej. Kan du länka programmet med problemet?
