### ISSUE TITLE
Svtplay - Laddar, var god vänta...(I evighet)

### ISSUE THREAD

**Issue by Rockyjohan** [stefansundin/privatkopiera#169]
Försöker få ner adressen via chrome som vanligt men det står bara "Laddar, var god vänta..." i evighet och någon länk kommer aldrig.

**Comment by Rockyjohan** [comment]
Update! Det verkar funka på själva svtplay men försöker ladda ner ett inslag på svt.se(vilket har fungerar felfritt innan)
så alltså inget direkt problem med svtplay.

**Comment by stefansundin** [comment]
Kan du länka programmet med problemet?

**Comment by Rockyjohan** [comment]
Hej! Ursäkta sent svar.
Det verkar fungerar korrekt numera!
