### ISSUE TITLE
v0.3.8

### ISSUE THREAD

**Issue by earthdreams2007** [stefansundin/privatkopiera#173]
### Discussed in https://github.com/stefansundin/privatkopiera/discussions/142
Hej 
Får 404 fel när jag ska hämta på tv4 play. Är det nåt fel där nu?
mvh Christoffer
<div type='discussions-op-text'>

<sup>Originally posted by **stefansundin** November 27, 2022</sup>
- Fixade SVT Play efter att de ändrat på deras URL.
- Fixade TV4 efter att de också ändrat på grejor.
- Fixade lite på UR också bara för att.

Hoppas det fungerar ett tag nu!

**Full Changelog**: https://github.com/stefansundin/privatkopiera/compare/v0.3.7...v0.3.8

<hr /><em>This discussion was created from the release <a href='https://github.com/stefansundin/privatkopiera/releases/tag/v0.3.8'>v0.3.8</a>.</em></div>

**Comment by viktorlindgren** [comment]
TV4Play har ändra en del. Se #172 och stäng denna som dubblett.
