### ISSUE TITLE
nrk play

### ISSUE THREAD

**Issue by marcustns** [stefansundin/privatkopiera#178]
hej, tack på förhand :) test på svt play funkar tip topp men försöker ladda ner från nrk play men får return: 

HTTP error 404 Not Found
https://psapi.nrk.no/obsoleteproperty?endpoint=programs/FUHA06000801&property=HlsUrl&useragent=Mozilla%2f5.0: Server returned 404 Not Found

https://tv.nrk.no/serie/autofil/2001/FUHA06000801/avspiller

**Comment by stefansundin** [comment]
Hej. Har precis släppt v0.3.10 som fixar problemen med nrk.no och dr.dk.
