### ISSUE TITLE
Can't download from Urplay (https://urplay.se/serie/231358-en-varmare-planet) with Firefox 101.0.

### ISSUE THREAD

**Issue by VemArJag** [stefansundin/privatkopiera#183]
Can't download from urplay.se (https://urplay.se/serie/231358-en-varmare-planet) with Firefox 101.0.

**Comment by stefansundin** [comment]
Får du något felmeddelande? Tror du att det är för att din Firefox-version är gammal?

Jag brukar testa med Firefox ESR ibland, men jag gjorde inte det i den senaste uppdateringen. Detta för att det finns en ny ESR som är version 115.

Här är kommandot för programmet i fråga:

```
# avsnitt 1:
ffmpeg -i "https://streaming10.ur.se/urplay/_definst_/mp4:se/231000-231999/231361-21.mp4/playlist.m3u8" -vcodec copy -acodec copy -absf aac_adtstoasc "En varmare planet - Klimatet, växterna och djuren.mp4"

# avsnitt 2:
ffmpeg -i "https://streaming10.ur.se/urplay/_definst_/mp4:se/231000-231999/231360-21.mp4/playlist.m3u8" -vcodec copy -acodec copy -absf aac_adtstoasc "En varmare planet - Uppvärmda hav.mp4"
```

**Comment by stefansundin** [comment]
En trolig anledning till problemen kan vara att det verkar att man måste ladda om sidan innan tillägget förstår vilken video man tittar på. Jag tänkte inte på att testa det. UR använder ajax när man navigerar och tillägget har bara enkel tillgång till originalsidan som man först gick till. Så ladda om sidan varje gång före du försöker använda tillägget på urplay.se.

Så om du fick "Error: program is undefined" så är det troligt detta som gick fel.

**Comment by stefansundin** [comment]
Har fixat problemet i min senaste kommentar med bdb8c92. Men skulle vara bra om du kunde bekräfta om det var det enda problemet?
