### ISSUE TITLE
dr.dk undertexter

### ISSUE THREAD

**Issue by jonas9881** [stefansundin/privatkopiera#184]
Hej, jag ville ladda ner denna videon https://www.dr.dk/drtv/se/skattejaegerne_54685 först videon och sedan undertexten, men den behövde tydligen fler behörigheter (även om jag kan se videon) så klarar den tydligen inte läsa av den. Skulle det gå att lägga till lite kod så verktyget även funkar för den sidan?

Edit: för att kunna ladda ner det ändå utan verktyg så ladda ner "manifest" och öppna den i anteckningar och leta rätt efter den högsta bild kvalite som finns kopiera den och så hittar du den på sidan såhär: 
![image](https://github.com/stefansundin/privatkopiera/assets/118567144/4ef4dd12-fc15-44cf-abdb-dce53e154714)
Nu var bilden från försöket till ljud-nedladningen men samma princip för bild, och sedan använd det på detta sätt.

 ffmpeg -i https://drod22o.akamaized.net/all/clear/none/f6/5dee833eac5a611514fa08f6/00951607120/stream_fmp4/Skattejaegerne_e1182166f9694edcbb33f50adf1b2c28_3544_video.m3u8" -i "https://drod22o.akamaized.net/all/clear/none/f6/5dee833eac5a611514fa08f6/00951607120/stream_fmp4/Skattejaegerne_e1182166f9694edcbb33f50adf1b2c28_3544_audio.m3u8" "Skattjägarna S8E12.mkv"

Hoppas det funkar för er också.

**Comment by stefansundin** [comment]
Hej. Vill bara bekräfta att det här gäller meddelandet "Fler behörigheter krävs för den här sidan."?

När du får det meddelandet så behöver du bara klicka på den blåa knappen "Bevilja behörigheter". Då frågar webbläsarens om du verkligen vill ge Privatkopiera de nya behörigheterna som krävs. Efter att du beviljat det så fungerar Privatkopiera som vanligt på dr.dk.

Kan du bekräfta att det här var problemet och att knappen fungerar för dig? Tack.

**Comment by jonas9881** [comment]
Ja det funkar, men vad menas då med "Spokensubtitles" och "Standardvideo" som man kan välja emellan? Och undertexten fanns tydligen inte med. Är spokensubtitles inbäddad undertext?

**Comment by stefansundin** [comment]
> Ja det funkar

Okej, så originalproblemet var bara att du inte förstod hur man beviljar behörigheter? Har du något förslag på hur jag kan förbättra hur det presenteras?

> men vad menas då med "Spokensubtitles" och "Standardvideo" som man kan välja emellan?

Jag gissar på att det motsvarar det här alternativet:

![Screenshot 2023-09-11 at 20 27 47](https://github.com/stefansundin/privatkopiera/assets/1991151/0646f855-0856-4191-88f0-af916bea53b5)

Förmodligen borde tillägget välja Standardvideo som standard. Jag får ändra det.

> Och undertexten fanns tydligen inte med.

Verkar som att jag inte har lagt till stöd för undertexter på dr.dk. Jag ser att det finns referenser till undertexterna i datan dock.

**Comment by sketch3** [comment]
Kan ikke hente undertekster på dr.dk, f.eks. https://www.dr.dk/drtv/se/das-boot_-exitstrategier_393838.
Har givet de ønskede tilladelser og kan herefter hente "StandardVideo (HD-1080)" og "SpokenSubtitles (HD-1080)". De indeholder ikke undertekster. Mangler en mulighed for at hente undertekster og også gerne video i lavere opløsning.

**Comment by stefansundin** [comment]
Nu har v0.4.0 släppts och undertexter ska nu fungera på dr.dk.
