### ISSUE TITLE
TV4 fungerar ej

### ISSUE THREAD

**Issue by Bengt128** [stefansundin/privatkopiera#185]
https://www.tv4play.se/video/8ff56dd8e591e1854af1/crossfire
https://www.tv4play.se/video/a4077db34c9229914ff3/the-suburbans
https://www.tv4play.se/video/5885dd6782ccab19f7e9/plikten-och-k%C3%A4rleken
https://www.tv4play.se/video/bb37adc269d3725bfd45/lost-lives-club
https://www.tv4play.se/video/056530e73a78d6a52f3f/har-du-h%C3%B6rt-ryktet-om-morgans

**Comment by jonas9881** [comment]
Det verkar som att ingen går i fortsättningen, väldigt konstigt. Kanske har TV4 gjort en uppdatering som inte stöds ännu.

**Comment by stefansundin** [comment]
Verkar som att de har lagt till en koll till `https://avod-auth-alb.a2d.tv/oauth/refresh`. Om `Origin` headern innehåller `-` innan `://` så blockeras anropet.

Jag skrev lite fulkod och fick det att fungera igen men koden är riktigt ful just nu. Ska försöka förbättra den lite innan jag släpper ny version.

**Comment by jonas9881** [comment]
Utöver det valda ämnet så undrar jag vad "fulkod" menas?

**Comment by stefansundin** [comment]
https://sv.wikipedia.org/wiki/Fulkod

**Comment by robban00** [comment]
Väntar mig en förbättring :) 👍

**Comment by rogerrapp** [comment]
Helt rätt tänkt att hålla koden snygg Stefan.
Skriver du obegriplig kod får du färre som kan/har lust att hjälpa till m. felsökning och förbättringar + att du tröttnar själv förr eller senare.
Fortsätt göra det det du gör precis som du gör det.

**Comment by robban00** [comment]
Hur går det med förbättringen?

**Comment by stefansundin** [comment]
Jag har kommit fram till att det här blir enklare att lösa om jag flyttar tillägget över till Manifest Version 3 (MV3). Firefox har varit lite tröga på att implementera MV3 och det är skälet till att jag inte har försökt tidigare, men jag har gjort några snabba tester nu och det verkar som att stödet är bättre nu.

Så det blir en lite större omskrivning tror jag innan jag släpper uppdateringen. Det blir version 0.4.0. Min gissning är att jag släpper den om 1-2 veckor.

Men jag har förberett ett sätt för er att testa min fix i förväg. Ni kan ladda ned den här zip filen och extrahera den, och sedan ladda in den i Chrome om ni aktiverar utvecklarläge. **OBS: Den här fungerar inte i Firefox!!**

[privatkopiera-0.4.0-alpha1.zip](https://github.com/stefansundin/privatkopiera/files/12680624/privatkopiera-0.4.0-alpha1.zip)

Här finns det instruktioner hur man laddar ett tillägg i utvecklarläge: https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/

Efter att du laddat tillägget och öppnar det på en sida så ser du att versionen i hörnet är `v0.4.0 (alpha1)`.

Skriv gärna en kommentar om det fungerar och om någon annan sida har slutat fungera. Jag testade bara lite snabbt.

Om någon är intresserad av kodändringen så kan man titta på den här temporära branchen som jag skapade: https://github.com/stefansundin/privatkopiera/tree/tv4-fix-temp

**Comment by rogerrapp** [comment]
Linux Brave browser (Chrome)
Skapar fortfarande inget ffmpeg kommando.

Laddar var god vänta....

'Unrecognized mainfest key 'optional_host_permissions'
..
  "optional_permissions": [
    "downloads"
  ],
  **_"optional_host_permissions": [
    "https://psapi.nrk.no/",
    "https://isl.dr-massive.com/"_**
  ]
..

**Comment by stefansundin** [comment]
@rogerrapp Testa med Chrome som instruktionerna tydligt sa. Var det verkligen så otydligt? 🙄

**Comment by rogerrapp** [comment]
Sorry, My bad. Det funkar med Chromium Browser.  
Jag är ju också ingenjör och kan/vill därför inte läsa en skriven instruktion.
Dessutom är jag man :-)

**Comment by rogerrapp** [comment]
Ja, det är ju en  gammal version av brave-browser i Ubuntu 20.04 LTS apt-repo.

Ni som kör brave-browser på Ubuntu Linux och har installerat 'by the book', installera från snap-repot istället. 
Då får man en nyare version där  040-alpha1 fungerar.

- **_Exportera/spara bokmärkena_**
- apt remove brave-browser
- snap install brave

Observera: Man får inte automatiskt bokmärkena från apt-versionen.
(Jag fick importera manuellt )

Sen måste man slå av annonsblockeraren i brave som är aktiverad som standard.
Nu funkar det som tidigare.

**Comment by simon2874** [comment]
Jag testade att ladda ner ett avsnitt av 'Efter fem' på TV4play med ditt nya tillägg, men när jag spelar upp filmen är ljud och bild inte synkroniserade.

**Comment by robban00** [comment]
> Jag har kommit fram till att det här blir enklare att lösa om jag flyttar tillägget över till Manifest Version 3 (MV3). Firefox har varit lite tröga på att implementera MV3 och det är skälet till att jag inte har försökt tidigare, men jag har gjort några snabba tester nu och det verkar som att stödet är bättre nu.
> 
> Så det blir en lite större omskrivning tror jag innan jag släpper uppdateringen. Det blir version 0.4.0. Min gissning är att jag släpper den om 1-2 veckor.
> 
> Men jag har förberett ett sätt för är att testa min fix i förväg. Du kan ladda ner den här zip-filen och extrahera den, och sedan ladda den i Chrome för att aktivera utvecklarläge. **OBS: Den här fungerar i Firefox!!**
> 
> [privatkopiera-0.4.0-alpha1.zip](https://github.com/stefansundin/privatkopiera/files/12680624/privatkopiera-0.4.0-alpha1.zip)
> 
> Här finns instruktioner hur man laddar ett tillägg i utvecklarläge: https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/
> 
> Efter att du laddat tillägget och öppnar det på en sida så ser du att versionen i hörnet är `v0.4.0 (alpha1)`.
> 
> Skriv gärna en kommentar om det fungerar och om någon annan sida har slutat fungera. Jag testade bara lite snabbt.
> 
> Om någon är intresserad av kodändringar så kan man titta på den här temporära branschen som jag skapade: https://github.com/stefansundin/privatkopiera/tree/tv4-fix-temp

Funkar klockrent :) :+1:

**Comment by jonas9881** [comment]
Var kan jag ladda ner gamla versioner av din privatkopiera någonstans? Skulle vara bra iallafall, att man då kan välja vilken som passar bäst på vad man gör för arbete.

**Comment by stefansundin** [comment]
> Var kan jag ladda ner gamla versioner av din privatkopiera någonstans? Skulle vara bra iallafall, att man då kan välja vilken som passar bäst på vad man gör för arbete.

Om du använder Firefox så kan du installera en gammal version här: https://addons.mozilla.org/en-US/firefox/addon/privatkopiera/versions/

Chrome har ingen möjlighet att installera en gammal version. Du får använda git och ladda ned källkoden och installera den gamla versionen på det viset.

**Comment by jonas9881** [comment]
Jag använder chrome, men vet hur jag laddar ner den och sedan kan bara ladda upp den vid "Extentions" som jag gjorde med 0.4.0.

**Comment by H2SO4JB** [comment]
Tack Stefan, jag kan bekräfta att 0.4.0 Alpha funkar perfekt just nu i alla fall. Jag använder Brave.

**Comment by stefansundin** [comment]
Har en ny alpha som kan testas av de som känner sig modiga. Jag har gjort om en hel del i koden så det är mindre fulkod i stort sätt. Det finns fortfarande en del att göra men det är ett bra steg på vägen.

Ändringar:
- Har flyttat runt på en massa kod och det är lite modernare JavaScript nu.
- Uppdaterat bootstrap vilket ger bättre dark mode.
- TV4Play cachar nu access token.
- Det ska fungera i Firefox nu också.
- Om man försöker ladda tillägget i en gammal version av Chrome så ska den nog klaga.

Ladda ned till Chrome: [privatkopiera-0.4.0-alpha2-chrome.zip](https://github.com/stefansundin/privatkopiera/files/12843332/privatkopiera-0.4.0-alpha2-chrome.zip)

Ladda ned till Firefox: [privatkopiera-0.4.0-alpha2-firefox.zip](https://github.com/stefansundin/privatkopiera/files/12843334/privatkopiera-0.4.0-alpha2-firefox.zip)

I Firefox så kan du ladda tillägget i `about:debugging`. Till skillnad från Chrome så behöver du inte extrahera zip filen, men tillägget försvinner också när du stänger Firefox.

Testa gärna alpha2 med andra tjänster och inte bara TV4. Det kan hända att jag strulade till det för andra play-tjänster, och det vore bra att upptäcka det nu.

Hör av er hur det fungerar.

**Comment by H2SO4JB** [comment]
0.4.0 Alpha 2 funkar fint för mig i Brave. 👍🏻
Har testat både SVT Play och TV4 Play.

**Comment by stefansundin** [comment]
Jag testade alpha2 mest i Firefox så jag märkte inte att vissa sidor inte fungerar i Chrome (t.ex. sverigesradio, nrk, dr.dk). Så om du använder Chrome så vill du nog använda alpha1 istället.

Om du stöter på den här buggen så ser du det här meddelandet:

> Error: chrome.tabs.executeScript is not a function

Jag släpper nog alpha3 typ nästa helg med en lösning på det här problemet.

**Comment by stefansundin** [comment]
Om det är någon som testar 0.4.0 med Firefox så finns det tyvärr ett litet irritationsmoment. Det är nämligen en punkt under ikonen som inte går att bli av med.

![Screenshot 2023-10-10 at 21 09 24](https://github.com/stefansundin/privatkopiera/assets/1991151/4bde9caf-2c7c-4a29-85c1-17e1ef8809fa)

Det verkar vara en bugg i Firefox som är rapporterad här: https://bugzilla.mozilla.org/show_bug.cgi?id=1851083

Det finns ingenting jag kan göra åt det. Förhoppningsvis fixas det snart.

**Comment by stefansundin** [comment]
Här är alpha3 som utlovat med fix för "chrome.tabs.executeScript" felet.

Chrome: [privatkopiera-0.4.0-alpha3-chrome.zip](https://github.com/stefansundin/privatkopiera/files/12910851/privatkopiera-0.4.0-alpha3-chrome.zip)

Firefox: [privatkopiera-0.4.0-alpha3-firefox.zip](https://github.com/stefansundin/privatkopiera/files/12910852/privatkopiera-0.4.0-alpha3-firefox.zip)

Jag har tyvärr inte tid att jobba på Privatkopiera i de närmaste veckorna, så det blir nog skarpt släpp för v0.4.0 någon gång i November. Så om du som läser detta har väntat på en fix för TV4 att släppas så vill jag uppmana dig att försöka med alpha3 istället för att fortsätta vänta.

Om ni stöter på några problem så skriv gärna här, men jag kanske inte svarar eller löser det fören i November.

Ha det bra allihopa!

**Comment by robban00** [comment]
https://www.tv4play.se/video/cf0ab9fbb69164c0a4fd/räddningsuppdraget funkar inte. 3 avsnitt av programmet samma för alla 3. någon som vet varför?

**Comment by PeterWaldero** [comment]
_> [https://www.tv4play.se/video/cf0ab9fbb69164c0a4fd/räddningsuppdraget](https://www.tv4play.se/video/cf0ab9fbb69164c0a4fd/r%C3%A4ddningsuppdraget) funkar inte. 3 avsnitt av programmet samma för alla 3. någon som vet varför?_

Din länk verkar gå till TV-serien Estonia, och den har väl inte haft premiär än, så jag gissar att det är därför som nedladdningen inte fungerar.

**Comment by PeterWaldero** [comment]
Nu har Estonia haft premiär. Det trista är dock att delar av dialogen är på estniska, och textning funkar inte då du använder Privatkopiera för TV4...

**Comment by Lunarwalker60** [comment]
Använd detta kommando:
"ffmpeg.exe" -i "https://vod.streaming.a2d.tv/6d2a71a9-5428-42ac-b4c3-d676e496ddd5/a5f039a0-69c2-11ee-a5e1-ddfdc72853df_20559311.ism/a5f039a0-69c2-11ee-a5e1-ddfdc72853df_20559311-textstream_swe=1000.m3u8" "Estonia - S01E01 - Räddningsuppdraget.srt"

Studera detta kommando och jämför det med det kommando Du använder för videon från TV4 så ser Du hur Du kan fixa det själv med några manuella steg  framöver tills Stefan får tid att fixa det.

**Comment by robban00** [comment]
> Använd detta kommando: "ffmpeg.exe" -i " [https://vod.streaming.a2d.tv/6d2a71a9-5428-42ac-b4c3-d676e496ddd5/a5f039a0-69c2-11ee-a5e1-ddfdc728053dc721053dc721853dc728053dc728053dc72853dc728053dc728053dc728053dc72853dc72853dc728053dc72853dc72853dc72853dc 2- 11ee-a5e1-ddfdc72853df_20559311-textstream_swe=1000.m3u8 " "](https://vod.streaming.a2d.tv/6d2a71a9-5428-42ac-b4c3-d676e496ddd5/a5f039a0-69c2-11ee-a5e1-ddfdc72853df_20559311.ism/a5f039a0-69c2-11ee-a5e1-ddfdc72853df_20559311-textstream_swe=1000.m3u8) Estland - S01E01 - Räddningsuppdraget.srt"
> 
> Studera detta och jämför det med kommandot Du använder för videon från TV4 så ser Du hur Du kan fixa det själv med några manuella steg framöver tills Stefan får tid att fixa det.


Fick ner den men då saknar den undertext. Är det någon som vet hur man kan fixa det?

**Comment by PeterWaldero** [comment]
Ja, alltså Lunarwalker60 har ju beskrivit kommandot för att få ner undertexen till det första avsnittet av Estonia. Jag fick det att fungera enligt hans beskriving. Så vad händer lyckas du inte få ner SRT-filen, eller är det så att du har fått hem filen, min ingen text visas i filmen...?

**Comment by iamesh-dev** [comment]
Fungerar Klockerent för allt material som inte är plus 

Har knåpat lite och kommit så långt att jag kan ladda ner rörlig bild utan ljud med paketet Play+ (med reklam) 59Kr/mån 

Intressant problem

**Comment by BacchusFLT** [comment]
Spännande! Kämpa vidare!

/Pontus Berg

Den sön 24 dec. 2023 kl 21:20 skrev webberian ***@***.***>:

**Comment by stefansundin** [comment]
Nu har v0.4.0 släppts så hoppas det fungerar för allihopa. Om någon installerade alpha versionerna så avinstallera dem och aktivera den vanliga versionen.
