### ISSUE TITLE
kan inte ladda ner UR play provat installera om ff mpeg men får följande svar Error: Cannot read properties of undefined (reading 'streamingInfo') vad gör jag för fel

### ISSUE THREAD

**Issue by jabbadabbado** [stefansundin/privatkopiera#190]

**Comment by jonas9881** [comment]
Funkar för mig, finns det något exempel som ej funkar för dig?

Testade den nya versionen som han nämnde som ej funkar testa använda den gamla om du har den.

[Länk](https://github.com/stefansundin/privatkopiera/issues/185)

**Comment by stefansundin** [comment]
@jabbadabbado Ditt största fel är att du inte länkar ett program som instruktionerna säger.

> provat installera om ff mpeg

Varför provade du det? Felet som du skriver kommer ju innan du ens kopierar ett kommando, så varför installerade du om ffmpeg?

Ganska slarvigt skriven buggrapport. Ägna några minuter till att göra det förståeligt tack!

> Testade den nya versionen som han nämnde här som ej funkar testa använda den gamla om du har den.

Det ska inte vara någon skillnad på v0.3.10 och v0.4.0-alpha1 som berör urplay, men om du hittar en skillnad så **INKLUDERA EN URL**.

**Comment by jonas9881** [comment]
Tycker du är lite "bossig" så var isåfall som en lärare nu om du ändå ska lära ut. Det problemet innebär är att man inte har valt program i urplay därav kommer inte någon länk upp i privatkopiera.

Och jag behöver inte ge någon länk om jag inte vill, men det var ett fel jag gjorde, och kan göra fler på vägen. "Om man aldrig gör fel, så kan man aldrig lära sig"

Vill inte heller låta bossig, men fick bara den känslan direkt när jag läste.

Iallafall bra jobbat men programmet, väldigt duktigt att programera den. Jag själv arbetar med "blockprogramering" men det är det längsta jag kan komma. För utan bra engelska och svåra ord så blir det svårt att lära sig programering på andra sätt, så du är faktiskt duktig och det uppskattas.

**Comment by jabbadabbado** [comment]
Vissa program fungerar alldeles utmärkt för mig. En del går inte då programmet inte verkar hitta "strömmen". Får då följande till svar ( på ett ungefär) "om jag är säker att programmet har sänts" sitter på mobilen så är lite knepigt att förklara exakt.Den 29 sep. 2023 22:59 skrev jonas9881 ***@***.***>:
Funkar för mig, finns det något exempel som ej funkar för dig?
Testade den nya versionen som han nämnde som ej funkar testa använda den gamla om du har den.
Länk

**Comment by stefansundin** [comment]
> Tycker du är lite "bossig" så var isåfall som en lärare nu om du ändå ska lära ut.

Ja, du har rätt att jag inte uttryckte mig på det finaste sättet. Får be om ursäkt om det.

Det är bara att det är svårt för mig att hjälpa till om jag inte får tillräckligt med information. Också så har mitt intresse för Privatkopiera minskat rejält, använder det inte så ofta själv längre. Min motivation för det här projektet lider.

Jag borde kanske ta en paus istället och återkomma när jag har mer tid.

> Och jag behöver inte ge någon länk om jag inte vill

Utan länk så kan man tyvärr inte förvänta sig någon hjälp heller.

**Comment by jabbadabbado** [comment]
Satt i helgen på mobilen och det är inte så jädra tvärlätt och svara på dina lite uttalanden. Jag är ingen expert det är du så du får leva med att saker och ting inte blir perfekta det får vi nog alla göra.

Jag installerade om ffmpeg då jag trodde att det kunde vara skadat och jag visste inte bättre provade allt, hoppas svaret duger.

Här är länken : https://urplay.se/serie/179424-en-rolig-historia

Bifogar också en skärmdump som programmet ger
[https://www.bing.com/th?id=OVP.V4qjK5-SC4ub8VFeI1o1VQIIEk&pid=Api]<https://urplay.se/serie/179424-en-rolig-historia>
En rolig historia | UR Play<https://urplay.se/serie/179424-en-rolig-historia>
Ann och Henrik ser ett historieprogram på tv och börjar fundera över det där med tid. Hur höll man reda på tiden innan man hade klocka? Vem uppfann klockan? Och vad är egentligen tid? Ann och Henrik färdas till järnålderns bondesamhälle för att ta reda på hur man kom i tid utan klocka. De reser till medeltidens städer för att ...
urplay.se


________________________________
Från: Stefan Sundin ***@***.***>
Skickat: den 29 september 2023 23:13
Till: stefansundin/privatkopiera ***@***.***>
Kopia: jabbadabbado ***@***.***>; Mention ***@***.***>
Ämne: Re: [stefansundin/privatkopiera] kan inte ladda ner UR play provat installera om ff mpeg men får följande svar Error: Cannot read properties of undefined (reading 'streamingInfo') vad gör jag för fel (Issue #190)


@jabbadabbado<https://github.com/jabbadabbado> Ditt största fel är att du inte länkar ett program som instruktionerna säger.

provat installera om ff mpeg

Varför provade du det? Felet som du skriver kommer ju innan du ens kopierar ett kommando, så varför installerade du om ffmpeg?

Ganska slarvigt skriven buggrapport. Ägna några minuter till att göra det förståeligt tack!

Testade den nya versionen som han nämnde här som ej funkar testa använda den gamla om du har den.

Det ska inte vara någon skillnad på v0.3.10 och v0.4.0-alpha1 som berör urplay, men om du hittar en skillnad så INKLUDERA EN URL.

**Comment by stefansundin** [comment]
Verkar som att det här fungerar så stänger tråden.
