### ISSUE TITLE
SVT har nytt URL-format

### ISSUE THREAD

**Issue by botanicblow** [stefansundin/privatkopiera#196]
Svt har påbörjat ett nytt format för sina länkar, ex: https://www.svt.se/videoplayer-embed/jXApWXa och nu vill inte mjukvaran ta ned filen. Nått du kan kika på?

**Comment by Bub0** [comment]
> Svt har påbörjat ett nytt format för sina länkar, ex: https://www.svt.se/videoplayer-embed/jXApWXa och nu vill inte mjukvaran ta ned filen. Nått du kan kika på?

Vet inte hur du fick den länken men https://www.svtplay.se/video/jXApWXa/kaffet-med-olof-wretling
Funkar utan problem, testa att gå till svtplay direkt. 😉

**Comment by botanicblow** [comment]
@Bub0 tyvärr hjälper det ej. Det finns ett gäng sidor på svt som kräver att det är formatet "videoplayer-embed". Ex. https://svt.se/videoplayer-embed/jGVEkX9

**Comment by botanicblow** [comment]
@stefansundin är det en lätt fix? Kan absolut slänga in ett gäng kronor i kaffekassan.

**Comment by Bub0** [comment]
> @Bub0 tyvärr hjälper det ej. Det finns ett gäng sidor på svt som kräver att det är formatet "videoplayer-embed". Ex. https://svt.se/videoplayer-embed/jGVEkX9

My bad missade att du inte var på svtplay.
Under tiden kan du ju använda utvecklarläget i webbläsaren för att hitta länken till m3u8 eller mpd. 🙂
Ser ut såhär, https://svt-vod-4k.akamaized.net/d0/world/20231101/e181d4ae-9aba-4f91-a946-1366202aa333/dash-full.mpd
Ser

**Comment by botanicblow** [comment]
@Bub0 Tyvärr verkar inte sidorna jag kikar på ha dessa. Har kikat i källkoden och finner endast en referens till 'm3u8' i ett kommentar och inte heller någon 'mpd' förutom som någon referens i js. Ingen url i stilen du nämner ovan tyvärr.

**Comment by Bub0** [comment]
> @Bub0 Tyvärr verkar inte sidorna jag kikar på ha dessa. Har kikat i källkoden och finner endast en referens till 'm3u8' i ett kommentar och inte heller någon 'mpd' förutom som någon referens i js. Ingen url i stilen du nämner ovan tyvärr.

Öppna webbläsaren, högerklicka, inspektera, välj nätverk, börja spela det du vill ha, filtrera efter m3u8 eller mpd. 🙂
Texter är oftast srt, vtt eller webvtt media kan vara mp4 också, beror på siten.
lycka till!

**Comment by botanicblow** [comment]
@Bub0 Jag är med på vad du menar men i detta fall så är det inte görbart. Sidan som har detta format (https://svt.se/videoplayer-embed/jGVEkX9) har ett gäng mp4:or under "Network" men det är många - jättemånga. Får vänta och se vad @stefansundin har att säga. :)

**Comment by Lunarwalker60** [comment]
Rostmacka har visningspremiär på fredag 17/11. Efter det finns den förmodligen i den vanliga versionen att ladda ner. För att ladda ner den segmenterade version som finns nu måste man lokalisera rätt m3u8-fil som ger ffmpeg rätt ände av tråden att börja nysta i så att säga.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2023-11-15, 11:39 botanicblow ***@***.***> wrote:

   
  @Bub0 Jag är med på vad du menar men i detta fall så är det inte görbart. Sidan som har detta format (https://svt.se/videoplayer-embed/jGVEkX9) har ett gäng mp4:or under "Network" men det är många - jättemånga. Får vänta och se vad @stefansundin har att säga. :)

**Comment by botanicblow** [comment]
> Rostmacka har visningspremiär på fredag 17/11. Efter det finns den förmodligen i den vanliga versionen att ladda ner. För att ladda ner den segmenterade version som finns nu måste man lokalisera rätt m3u8-fil som ger ffmpeg rätt ände av tråden att börja nysta i så att säga.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2023-11-15, 11:39 botanicblow ***@***.***> wrote: @Bub0 Jag är med på vad du menar men i detta fall så är det inte görbart. Sidan som har detta format (https://svt.se/videoplayer-embed/jGVEkX9) har ett gäng mp4:or under "Network" men det är många - jättemånga. Får vänta och se vad @stefansundin har att säga. :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Yes, jag hör dig. Andra avsnitt av rostmacka har url-formatet https://svt.se/videoplayer-embed/12345678, nu är det dock https://svt.se/videoplayer-embed/jGVEkX9 på denna. De andra går att ta hem utan problem, det är denna som har 'jGVEkX9' som är problemet.

**Comment by Lunarwalker60** [comment]
Vänta till fredag kl 02:00...--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2023-11-15, 15:42 botanicblow ***@***.***> wrote:

   
   
   Rostmacka har visningspremiär på fredag 17/11. Efter det finns den förmodligen i den vanliga versionen att ladda ner. För att ladda ner den segmenterade version som finns nu måste man lokalisera rätt m3u8-fil som ger ffmpeg rätt ände av tråden att börja nysta i så att säga.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2023-11-15, 11:39 botanicblow @.> wrote: @Bub0 Jag är med på vad du menar men i detta fall så är det inte görbart. Sidan som har detta format (https://svt.se/videoplayer-embed/jGVEkX9) har ett gäng mp4:or under "Network" men det är många - jättemånga. Får vänta och se vad @stefansundin har att säga. :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> 
   
  Yes, jag hör dig. Andra avsnitt av rostmacka har url-formatet https://svt.se/videoplayer-embed/12345678, nu är det dock https://svt.se/videoplayer-embed/jGVEkX9 på denna. De andra går att ta hem utan problem, det är denna som har 'jGVEkX9' som är problemet.

**Comment by Lunarwalker60** [comment]
Nu finns det programmet i vanlig version att tanka hem. Del 1 & 2 är hemma, med text.

 
 

Sent: Wednesday, November 15, 2023 at 3:42 PM

**Comment by botanicblow** [comment]
> Nu finns det programmet i vanlig version att tanka hem. Del 1 & 2 är hemma, med text.     Sent: Wednesday, November 15, 2023 at 3:42 PM From: "botanicblow" ***@***.***> To: "stefansundin/privatkopiera" ***@***.***> Cc: "Lunarwalker60" ***@***.***>, "Comment" ***@***.***> Subject: Re: [stefansundin/privatkopiera] SVT har nytt URL-format (Issue #196)   Rostmacka har visningspremiär på fredag 17/11. Efter det finns den förmodligen i den vanliga versionen att ladda ner. För att ladda ner den segmenterade version som finns nu måste man lokalisera rätt m3u8-fil som ger ffmpeg rätt ände av tråden att börja nysta i så att säga.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2023-11-15, 11:39 botanicblow @.> wrote: @Bub0 Jag är med på vad du menar men i detta fall så är det inte görbart. Sidan som har detta format (https://svt.se/videoplayer-embed/jGVEkX9) har ett gäng mp4:or under "Network" men det är många - jättemånga. Får vänta och se vad @stefansundin har att säga. :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> Yes, jag hör dig. Andra avsnitt av rostmacka har url-formatet https://svt.se/videoplayer-embed/12345678, nu är det dock https://svt.se/videoplayer-embed/jGVEkX9 på denna. De andra går att ta hem utan problem, det är denna som har 'jGVEkX9' som är problemet. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Fast det hjälper fortfarande inte. Det finns mängder med program/avsnitt/serier som har formatet https://svt.se/videoplayer-embed/jGVEkX9 som ej går att spara ned. Det bästa vore ju ifall Privatkopiera kunde ha en funktion där svt.se/videoplayer-ember/XXXXXXXX går att nyttja oavsett ifall det är siffror, bokstäver, alfanumeriskt etc.

**Comment by stefansundin** [comment]
I https://github.com/stefansundin/privatkopiera/commit/826e583754c5b6069fe71dc25a83c42b741347fc så har jag ändrat så att https://www.svt.se/videoplayer-embed/jXApWXa fungerar. Får hoppas att det inte pajjar andra program som ligger under `svt.se/videoplayer-embed/`. Om det gör det så kan ni länka programmen som slutar fungera.

Den här fixen kommer i v0.4.0 som förhoppningsvis kommer ut snart. Håller den här tråden öppen tills v0.4.0 har släppts.
