### ISSUE TITLE
Fel: API svarade med 400

### ISSUE THREAD

**Issue by Tooxic** [stefansundin/privatkopiera#20]
Får denna error när jag försöker ladda ner ifrån svtplay

![image](https://user-images.githubusercontent.com/33166817/54784285-be319e80-4c23-11e9-9002-e8792b4789e1.png)

**Comment by Bub0** [comment]
Uppdatera till v0.1.10 :-)

Den tor 21 mars 2019 21:53Tooxic <notifications@github.com> skrev:

**Comment by Tooxic** [comment]
Thank you.
