### ISSUE TITLE
tv4 play: Laddar, var god vänta

### ISSUE THREAD

**Issue by sin8o** [stefansundin/privatkopiera#200]
Hej!
 Problem med tv4 play. får meddelandet "Laddar, var god vänta ...",
 har provat med chrome och firefox. kör w11.

 har testat:
 https://www.tv4play.se/video/d08a78f2c33addf34585/johan-glans-sommarturne-en-standupshow
 https://www.tv4play.se/video/1d7416fa8d285d93d445/avsnitt-2
 och lite klipp och nyheter

 svt ser ut att fungera, har inga problem där.
 dk och nrk ser oxå ut att fungera.
 
 Vet inte om jag gör något fel eller om tv4 har ändrat något.

 Tv4 har ju ändrat så man får upp en reklamruta när man pausar,
då kan man inte stanna och titta noggrannare på något, mycket irriterande.

Tack för att du hjälper till så man får lite valuta för sina stim pengar.

**Comment by stefansundin** [comment]
Dubblett av https://github.com/stefansundin/privatkopiera/issues/185.

Fixas i nästa version som är nära förestående.
