### ISSUE TITLE
Unrecognized option 'absf'

### ISSUE THREAD

**Issue by delit** [stefansundin/privatkopiera#208]
### Innan du skickar in hjälpförfrågan

- [X] Jag förstår att Privatkopiera och FFmpeg inte kan ladda hem vissa filmer som har extra kopieringsskydd och kryptering.
- [X] Har kollat om det [redan finns en buggrapport](https://github.com/stefansundin/privatkopiera/issues) om det här.
- [X] Har kollat om det [redan finns en diskussionstråd](https://github.com/stefansundin/privatkopiera/discussions) om det här.
- [X] Tänkt efter om det här kanske passar bättre som [en diskussionstråd](https://github.com/stefansundin/privatkopiera/discussions).

### Länk till video du behöver hjälp med

https://www.svtplay.se/lista/svtId_eYqw5d6/historien-om-sverige

### Kryssa i den här rutan om alla klipp på sidan har slutat fungera

- [X] Alla klipp på sidan har slutat fungera

### Beskriv vad som inte fungerar

Jag får följande fel när jag försöker ladda ner från SVT Play: 

```
Unrecognized option 'absf'.
Error splitting the argument list: Option not found
```

- Använder Windows 11. 
- FFMPEG.exe ligger i följande mapp: C:\Path_ffmpeg.
- Har testat flera olika versioner av ffmpeg på deras sida (bland annat [ffmpeg-master-latest-win64-gpl.zip]).
- Har testat med både Chrome och FF plugin. 
- Har testat att lägga till mappen under Environment Variables > Path. 

Vad kan jag göra för att undvika felet? 

```
C:\Path_ffmpeg>ffmpeg -i "https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-video-avc-1920x1080p25-3082/hls-video-avc-1920x1080p25-3082.m3u8" -i "https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-audio-sv-aac-2ch-192/hls-audio-sv-aac-2ch-192.m3u8" -i "https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt" -vcodec copy -acodec copy -absf aac_adtstoasc "Historien om Sverige - 1. Stenåldern, ca 14.500 - 3700 år sedan.mp4"
ffmpeg version N-113212-g42982b5a5d-20240104 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20240104
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 37.100 / 60. 37.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 16.100 /  9. 16.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Unrecognized option 'absf'.
Error splitting the argument list: Option not found
```

**Comment by stefansundin** [comment]
Hej!

Tack för rapporten. Verkar som att ffmpeg har tagit bort `-absf` i den senaste versionen. Kan du testa byta ut `-absf` med `-bsf:a`?

Jag ska försöka titta lite närmare på det här lite senare, kommer nog behöva släppa en ny version som använder den nya syntaxen.

Från https://github.com/FFmpeg/FFmpeg/blob/master/Changelog:

>    * -vbsf/-absf/-sbsf options were removed and replaced by a -bsf option which
>      uses stream specifiers. Use -bsf:v/a/s instead of the old options.

**Comment by delit** [comment]
> Kan du testa byta ut -absf med -bsf:a?

Tack! Nu funkade det.

**Comment by stefansundin** [comment]
Har släppt v0.4.1 nu som fixar det här.
