### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by robban00** [stefansundin/privatkopiera#22]
Jag kommer inte år privatkopiera på Firefox p.g.a. inaktivering :( .
Osignerad tillägg, kan du lösa det tror du?
tack på förhand..

**Comment by robban00** [comment]
kunde inte verifieras står det

**Comment by Bub0** [comment]
Hade samma igår och löste det med det här,
https://support.mozilla.org/en-US/kb/about-config-editor-firefox
Lycka till! :-)

Den sön 5 maj 2019 11:21robban00 <notifications@github.com> skrev:

**Comment by Bub0** [comment]
Fel länk sry. Här!
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users

Den sön 5 maj 2019 11:34Rickard <sthcoy@gmail.com> skrev:

**Comment by robban00** [comment]
Hittade vad felet är med Firefox  https://www.sweclockers.com/forum/trad/1556682-firefox-jattebugg-alla-addons-stangs-av-for-alla-anvandare
