### ISSUE TITLE
Svt Barn funkar inte längre sedan ett tag tillbaka

### ISSUE THREAD

**Issue by Lizerd** [stefansundin/privatkopiera#26]

**Comment by Bub0** [comment]
Funkar här om inte annat. https://www.svtplay.se/greta-gris :-)

Den ons 29 apr. 2020 10:31Mike Kallberg <notifications@github.com> skrev:

**Comment by stefansundin** [comment]
Greta Gris fungerar även för mig. Länka alltid om du vill rapportera något som inte funkar. Tack!

**Comment by stefansundin** [comment]
Okej, jag ser nu länken som fanns innan den togs bort. Den här fungerar inte: https://www.svt.se/barnkanalen/barnplay/alfons-aberg/KwRWg4j

För en tillfällig workaround kan du ta `KwRWg4j` från URLen och lägga på den efter `https://api.svt.se/video/`: https://api.svt.se/video/KwRWg4j.

Kopiera sedan en .m3u8 URL och klistra in i ett ffmpeg kommando.

Fixar nog detta till nästa version.

**Comment by stefansundin** [comment]
Fixat i v0.2.1. https://github.com/stefansundin/privatkopiera/commit/0a5c9803006d03d22ef23bce1960b68bfdf4e69d
