### ISSUE TITLE
SVT Play fungerar inte

### ISSUE THREAD

**Issue by Bub0** [stefansundin/privatkopiera#27]
Får inte fram några länkar på Svtplay, varken i Chrome eller Firefox. :-(

**Comment by robban00** [comment]
Inte jag heller :(

**Comment by stefansundin** [comment]
Verkar som att de ändrat på koden. https://www.oppetarkiv.se/ använder samma kod och det fungerar fortfarande, men förmodligen så slutar den också fungera så småningom. Ska försöka fixa inom några dagar.

**Comment by Bub0** [comment]
> Verkar som att de ändrat på koden. https://www.oppetarkiv.se/ använder samma kod och det fungerar fortfarande, men förmodligen så slutar den också fungera så småningom. Ska försöka fixa inom några dagar.

Underbart. 🙂Ingen stress! 👍

**Comment by 79Lindis** [comment]
Tack som 17, uppskattar ditt jobb, ingen stress, är så glad att detta tillägg finns.

**Comment by stefansundin** [comment]
Har nu släppt v0.2.2 som fixar detta. Versionen är redan tillgänglig för Firefox, men Chrome tar nog några dagar innan de har godkänt den nya versionen.

I Firefox så måste en ny behörighet beviljas. Det behövs inte i Chrome.

**Comment by zilverzufer** [comment]
Grymt! tackar och bockar! Donation skickad :-)

**Comment by morgonte** [comment]
Mitt Firefox (71,0 Körs på Linux Mint 19.3 MATE 64 bit) påstår att "Inga behörigheter krävs" för tillägget under fliken "Behörigheter". Privatkopiera uppmanar mig att "Bevilja behörigheter" när jag försöker använda det på Svtplay. Har jag missat nåt?

**Comment by Maltavius** [comment]
> Mitt Firefox (71,0 Körs på Linux Mint 19.3 MATE 64 bit) påstår att "Inga behörigheter krävs" för tillägget under fliken "Behörigheter". Privatkopiera uppmanar mig att "Bevilja behörigheter" när jag försöker använda det på Svtplay. Har jag missat nåt?

Det här är inget forum, skapa en ny bugg om du har problem.

**Comment by stefansundin** [comment]
> Mitt Firefox (71,0 Körs på Linux Mint 19.3 MATE 64 bit) påstår att "Inga behörigheter krävs" för tillägget under fliken "Behörigheter". Privatkopiera uppmanar mig att "Bevilja behörigheter" när jag försöker använda det på Svtplay. Har jag missat nåt?

Var god se https://github.com/stefansundin/privatkopiera/issues/11#issuecomment-639933374. Privatkopiera frågar efter behörigheter när det behöver dem. Förut så frågade tillägget om alla behörigheter när det installerades.

Om du skrollar ner lite på installationssidan (https://addons.mozilla.org/sv-SE/firefox/addon/privatkopiera/) så ser du:

<img width="426" alt="Screen Shot 2020-09-08 at 12 52 29" src="https://user-images.githubusercontent.com/1991151/92521557-46b64d00-f1d2-11ea-88e9-a38c07947607.png">

Du kan också läsa: https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions

Osäker på om jag ska behöva förklara detta på hemsidan. 🤔

**Comment by morgonte** [comment]
> > Mitt Firefox (71,0 Körs på Linux Mint 19.3 MATE 64 bit) påstår att "Inga behörigheter krävs" för tillägget under fliken "Behörigheter". Privatkopiera uppmanar mig att "Bevilja behörigheter" när jag försöker använda det på Svtplay. Har jag missat nåt?
> 
> Var god se [#11 (comment)](https://github.com/stefansundin/privatkopiera/issues/11#issuecomment-639933374). Privatkopiera frågar efter behörigheter när det behöver dem. Förut så frågade tillägget om alla behörigheter när det installerades.
> 
Aha! Nej, trots att jag tar bort och installerar om Privatkopiera så frågar det inte efter några behörigheter alls, trots att svtplay behöver det. När jag försöker fånga en ström på svtplay får jag fram knappen "Bevilja behörigheter" men det händer inget när jag klickar på den. Jag var osäker om det berodde på något handhavandefel från min sida, men det verkar inte så. Ska jag skapa en ny bugg på Github för detta?

**Comment by stefansundin** [comment]
> Aha! Nej, trots att jag tar bort och installerar om Privatkopiera så frågar det inte efter några behörigheter alls, trots att svtplay behöver det. När jag försöker fånga en ström på svtplay får jag fram knappen "Bevilja behörigheter" men det händer inget när jag klickar på den. Jag var osäker om det berodde på något handhavandefel från min sida, men det verkar inte så. Ska jag skapa en ny bugg på Github för detta?

Jaha, inget händer när du trycker på knappen? Det förklarar förvirringen. Ja, skapa gärna en ny bugg. Tack för att du rapporterar det.
