### ISSUE TITLE
Ingen ström identifierad från SVT-Play, varken i Chrome eller FF, därför skapas inget kommando för ffmpeg.

### ISSUE THREAD

**Issue by ollhy** [stefansundin/privatkopiera#28]

**Comment by stefansundin** [comment]
Kopia av #27. Kolla i listan över buggar som redan är öppna innan du öppnar en ny.

**Comment by Lunarwalker60** [comment]
Det verkar som att SVT skickar fragmenterade mp4-block som webläsaren pusslar ihop.
