### ISSUE TITLE
dr.dk

### ISSUE THREAD

**Issue by stefansundin** [stefansundin/privatkopiera#29]
Någon i undersökningen bad om stöd för dr.dk. Tog en snabb titt och det skulle nog inte vara alltför svårt att bygga.

Exempel: https://www.dr.dk/drtv/se/de-usaarlige-betjente_-i-krig-paa-noerrebro_197681

Data: https://isl.dr-massive.com/api/account/items/197681/videos?delivery=stream&device=web_browser&ff=idp%2Cldp&lang=da&resolution=HD-1080&sub=Anonymous

Det krävs en header för att hämta datan, annars får man `{"message":"Der er opstået en fejl. Prøv igen"}`. Man måste skicka `x-authorization: Bearer <token>`, där `<token>` kommer från sidans `localStorage["session.tokens"]`.

Exempel data:
```json
[
    {
        "accessService": "StandardVideo",
        "channels": 2,
        "deliveryType": "Stream",
        "drm": "None",
        "format": "video/hls",
        "resolution": "HD-1080",
        "height": 0,
        "isStreamLive": false,
        "language": "da",
        "name": "Video Resource",
        "subtitles": [
            {
                "format": "text/vtt;charset=utf-8",
                "isEmbedded": true,
                "isHardSubs": false,
                "language": "DanishLanguageSubtitles",
                "link": "https://drod05m-vh.akamaihd.net/p/allx/clear/download/35/5f3165deac5a611158644535/subtitles/HardOfHearing-17417617-828322b3-d901-48e5-b9c2-b08354acf0e6.vtt"
            }
        ],
        "url": "https://drod05m-vh.akamaihd.net/i/all/clear/streaming/35/5f3165deac5a611158644535/De-usaarlige-betjente-_71094d960d8e4d3187a203a76e5885f7_,300,512,1000,2200,3000,4300,.mp4.csmil/master.m3u8?cc1=name=Dansk~default=no~forced=no~lang=da~uri=https://drod05m-vh.akamaihd.net/p/allx/clear/download/35/5f3165deac5a611158644535/subtitles/HardOfHearing-17417617-828322b3-d901-48e5-b9c2-b08354acf0e6/playlist.m3u8",
        "width": 0
    }
]
```

Vill du att jag bygger stöd för dr.dk? Ett bra sätt att visa det är att donera.

**Comment by Ordval** [comment]
Förutsätter det (och det mesta utanför Sverige) 
att man ska' använda en VPN ?  
jag fattar det som att "TV4ever" skall klara det (DR), 
men det verkar som att man lovar för mycket.

Läst på: [Privatkopiera, Store](https://chrome.google.com/webstore/detail/privatkopiera/jhjhnecocacdbhlkjgpdacoibidhmgdf/related) men ser inget om det där.

Enda sättet för mig att donera (utelämnad historik) hade varit 
om jag hade haft tillgång till ett, emot dig, direkt bankgiro.

**Comment by Bub0** [comment]
Har du kollat på https://stefansundin.github.io/privatkopiera/?
Klicka på Andra doneringsalternativ: ;-)

**Comment by stefansundin** [comment]
Jag har nu lagt in stöd för dr.dk i v0.3.6. f0608c0bbd9d648b63159cde248f0cdcbe804197

Jag har inte testat det så mycket och det finns definitivt en del buggar. Om det inte fungerar så testa att ladda om hemsidan och klicka på Privatkopiera igen. I mina tester så har jag två tokens och just nu tar tillägget bara och testar med den första, och det fungerar inte alltid.

Jag tänker hålla den här tråden öppen ett tag. Om du har problem med en dr.dk video, så länka den här så kan jag ta en närmare titt.

**Comment by Ordval** [comment]
Toppen att du tog dig tid. 

Tycker mig läsa mellan raderna att det här ska gå med utländska program också (?).
Den länk du använder i den första posten är ett danskt program (vilket gör mig osäker)...
Danska program kan man förstås se och ladda ned utan att logga in.

Avinstallerade modulen och installerade den på nytt.

Nu kunde jag inte hitta det jag sökte, så jag tog bara nånting på måfå: 

"returned 403 Forbidden (access denied)"

>ffmpeg.exe -i "https://drod10i-vh.akamaihd.net/i/dk/clear/streaming/0a/600e65cca95a61159804920a/Windsor-dynastiet--San_33a256263a5647c1abd1845dcc1f9733_,300,512,1000,2200,3000,4300,.mp4.csmil/master.m3u8?cc1=name=Fremmedsprogstekster~default=yes~forced=no~lang=da~uri=https://drod10i-vh.akamaihd.net/p/allx/clear/download/0a/600e65cca95a61159804920a/subtitles/Foreign-17949930-a459d80d-bdf9-4152-9f47-3d2039d50349/playlist.m3u8&cc2=name=Dansk~default=no~forced=no~lang=da~uri=https://drod10i-vh.akamaihd.net/p/allx/clear/download/0a/600e65cca95a61159804920a/subtitles/Foreign_HardOfHearing-17949930-a459d80d-bdf9-4152-9f47-3d2039d50349/playlist.m3u8" -vcodec copy -acodec copy "Windsor-dynastiet- Sandheden om det britiske kongehus- Sæson 1 – Den modvillige konge.mkv"


> ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg develop
ers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfi
g --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libb
luray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --e
nable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-lib
twolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --
enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --e
nable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo
-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom
--enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enab
le-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va
--enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenm
pt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.101 / 58.101.101
  libavformat    58. 51.101 / 58. 51.101
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[https @ 00000000003bfe40] HTTP error 403 Forbidden
https://drod10i-vh.akamaihd.net/i/dk/clear/streaming/0a/600e65cca95a61159804920a
/Windsor-dynastiet--San_33a256263a5647c1abd1845dcc1f9733_,300,512,1000,2200,3000
,4300,.mp4.csmil/master.m3u8?cc1=name=Fremmedsprogstekster~default=yes~forced=no
~lang=da~uri=https://drod10i-vh.akamaihd.net/p/allx/clear/download/0a/600e65cca9
5a61159804920a/subtitles/Foreign-17949930-a459d80d-bdf9-4152-9f47-3d2039d50349/p
laylist.m3u8&cc2=name=Dansk~default=no~forced=no~lang=da~uri=https://drod10i-vh.
akamaihd.net/p/allx/clear/download/0a/600e65cca95a61159804920a/subtitles/Foreign
_HardOfHearing-17949930-a459d80d-bdf9-4152-9f47-3d2039d50349/playlist.m3u8: Serv
er returned 403 Forbidden (access denied)

Laddade ned det danska (TV-programmet) med Windows 7.

**Comment by stefansundin** [comment]
> Nu kunde jag inte hitta det jag sökte, så jag tog bara nånting på måfå:

Kan du länka videon?

**Comment by Ordval** [comment]
[2. Den modvillige konge](https://www.dr.dk/drtv/se/windsor_dynastiet_-sandheden-om-det-britiske-kongehus_-den-modvillige-konge_232763)

**Comment by stefansundin** [comment]
Jag får följande:

![Screen Shot 2021-04-01 at 19 02 02](https://user-images.githubusercontent.com/1991151/113372113-bfbaf480-931c-11eb-97c7-e1902024bbb7.png)

Förstod inte riktigt om du får samma felmeddelande?

Även om Privatkopiera verkar hitta ett kommando så ger det mig `403 Forbidden (access denied)` precis som dig. Om någon befinner sig i Danmark och kan testa om det fungerar där så vore det bra, man jag kan nog inte hjälpa mer med den här videon.

**Comment by Ordval** [comment]
> Förstod inte riktigt om du får samma felmeddelande?

Det får jag förstås: 
"Se DRTV på rejser i EU og EØS-lande
Bekræft fast dansk bopælsadresse med NemiD-
underskrift og fâ adgang til alle programmer på DRTV.

LOG IND OG BEKRÆFT"

Skulle nog ändå tro att det går med en bra proxy/ VPN.
Återigen är det, det här med att hitta en tillräckligt snabb å ena sidan 
och använda den jämt å andra, om det ska' vara ekonomiskt försvarbart. 
För att kommentera **Bub0** läste jag någonstans om Paypal, 
att det inte var så säkert med de personuppgifter man lämnar ut till dem. 
Därför har jag inte undersökt det närmare.

**Comment by Bub0** [comment]
Ovpn funkade när jag testade server i Danmark tidigare idag. :-)

Den fre 2 apr. 2021 14:04Ordval ***@***.***> skrev:

**Comment by Ordval** [comment]
Jorå, att det finns snabba VPN därute om man gör lite 
efterforskning det tvivlar jag inte på, men mitt problem 

> Enda sättet för mig att donera (utelämnad historik) hade varit 
om jag hade haft tillgång till ett, emot dig, direkt bankgiro. 

är just att jag inte kan betala med konto-/ kreditkort efter de 
alltmer hårda bestämmelserna, så jag har uteslutande satsat 
på de fria. "Klarna" ser jag inte att OVPN tar därför går det inte, 
men även om det skulle gå (vad de nu menar med: "cash payments" ?)
har jag isåfall bara dem och Freedom att välja mellan. 
Är ens VPN inte tillräckligt snabb för vardagsbruk, blir den 
avstängd för det mesta och bortglömd i de flesta fall, 
och inte "ekonomisk försvarbar" som jag skriver ovan. 
Jag skulle behöva en slags 'Pay-per-use'-lösning med Klarna.

Jag har studerat OpenVPN lite grann (trol. 2011; som är gratis 
om man lyckas själv) men inte lyckats programmera (?) den 
för egen del, och när det verkar bli så mycket jobb lägger jag 
av (personliga omständigheter), jag har hellre lagt energin 
på annat, men ingenting är egentligen uteslutet på området.....

**Comment by Bub0** [comment]
Om man inte är redo att lägga ner någon energi på något får man helt enkelt vara utan. Du gör något väldigt simpelt väldigt invecklat och omständigt.. 
Vad har du svårt att förstå med kontanter..? Läs deras FAQ och sluta förvänta dig att hela världen ska anpassa sig till dig och servera allt på silverfat........... 
> Jorå, att det finns snabba VPN därute om man gör lite
> efterforskning det tvivlar jag inte på, men mitt problem
> 
> > Enda sättet för mig att donera (utelämnad historik) hade varit
> > om jag hade haft tillgång till ett, emot dig, direkt bankgiro.
> 
> är just att jag inte kan betala med konto-/ kreditkort efter de
> alltmer hårda bestämmelserna, så jag har uteslutande satsat
> på de fria. "Klarna" ser jag inte att OVPN tar därför går det inte,
> men även om det skulle gå (vad de nu menar med: "cash payments" ?)
> har jag isåfall bara dem och Freedome att välja mellan.
> Är ens VPN inte tillräckligt snabb för vardagsbruk, blir den
> avstängd för det mesta och bortglömd i de flesta fall,
> och inte "ekonomisk försvarbar" som jag skriver ovan.
> Jag skulle behöva en slags 'Pay-per-use'-lösning med Klarna.
> 
> Jag har studerat OpenVPN lite grann (trol. 2011; som är gratis
> om man lyckas själv) men inte lyckats programmera (?) den
> för egen del, och när det verkar bli så mycket jobb lägger jag
> av (personliga omständigheter), jag har hellre lagt energin
> på annat, men ingenting är egentligen uteslutet på området.....

**Comment by stefansundin** [comment]
Hmm. Jag tror det är dags att coola ner diskussionen. 😬 

Låt oss försöka hålla oss på dr.dk i den här tråden. Vi kan diskutera VPN i en annan tråd.

**Comment by Bub0** [comment]
> Hmm. Jag tror det är dags att coola ner diskussionen. 😬
> 
> Låt oss försöka hålla oss på dr.dk i den här tråden. Vi kan diskutera VPN i en annan tråd.

Ursäkta. Dr.dk funkar fint, testade precis! :-)https://www.dr.dk/drtv/se/windsor_dynastiet_-sandheden-om-det-britiske-kongehus_-den-modvillige-konge_232763

**Comment by Ordval** [comment]
Du har fått det här med "silverfat" bakom foten, 
jag kan inte förklara tydligare än jag har gjort, 
"utelämnad historik" som jag skrivit ovan.
