### ISSUE TITLE
SVTPlay/Barnkanalen fungerade för två dagar sedan, men inte nu

### ISSUE THREAD

**Issue by Calle-L** [stefansundin/privatkopiera#3]
Hej Stefan,

Ursäkta att jag stör. Tack för ett fint Firefox-tillägg!

Häromdagen använde jag ditt tillägg och ffmpeg till att ladda hem några avsnitt från Barnkanalen, bl.a. denna (som tas bort efter idag): 
https://www.svt.se/barnkanalen/barnplay/pyjamashjaltarna/13133439 

Men idag fungerar inte den (eller de nästföljande avsnitten, som jag tänkte ta hem senast imorgon). Kan SVT ha ändrat något, eller är det något jag ändrat, tror du? (Windows 10, Firefox 52.0.2) Jag testade att disabla nya tillägg, men det gjorde ingen skillnad.

Jag fick heller inte till ffmpeg-kommandot för att ta hem den bästa videon och audion för detta avsnitt.

ffmpeg -i "https://svtplay10g-f.akamaihd.net/i/se/open/20170404/1377845-003A/PG-1377845-003A-PJMASKSPYJAM-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F1377845-003A.m3u8" -? copy -? copy -? ? "filnamn.mp4" 
typ...

Hmm - har du möjlighet att ta en snabb titt så vore det mycket uppskattat. Tack!

Mvh,
Calle

Edit: jag glömde felbeskrivningen: ingen ström eller något ffmpeg-kommando hittas/visas, även när man väntar en lång stund.

**Comment by stefansundin** [comment]
Hej Calle!

Det verkar som att de har uppdaterat lite, bland annat flyttat allt till https, vilket bråkar lite med tillägget. Jag ska försöka skicka ut en uppdatering när jag får tid, förhoppningsvis nu i veckan.

Tills dess så kan jag hjälpa dig manuellt. Här är kommandot för avsnittet du länkade:
```
ffmpeg -i "https://svtplay10g-f.akamaihd.net/i/se/open/20170404/1377845-003A/PG-1377845-003A-PJMASKSPYJAM-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "1377845-003A.mp4"
```

Gör en lista med fler avsnitt så kan jag ge dig motsvarande kommandon.

Mvh Stefan

**Comment by Calle-L** [comment]
Hej Stefan,

Ah, jag förstår - tack så mycket!
Efter att ha sett ffmpeg-kommandot ovan och jämfört med svaret du skrev till "Issue 1" förra året så lyckades jag få till det för nästkommande avsnitt. Tack!

Jag trodde du hade skrivit ett generellt svar, med placeholders, när du skrev -acodec copy -vcodec copy -absf aac_adtstoasc, men nu vet jag bättre! :-)

Jag kunde inte se "index_6_av" i Firefox-"Inspektören", men det kanske alltid blir den strängen där?

Tack igen - jätteschysst!

/Calle

**Comment by stefansundin** [comment]
`index_6_av.m3u8` motsvarar högsta kvaliten, om du använder `master.m3u8` så borde det nog automatiskt bli högsta kvaliten ändå.

P.S. Om Privatkopiera är värt guld för dig så kan du tacka med knappen här: https://stefansundin.github.io/privatkopiera/#donate :)

**Comment by Calle-L** [comment]
Tack, tack!

[Lite off-topic reflektion nedan]

Ja, en vänlig påminnelse om att donationer alltid är välkomna är ju inte fel. Jag är ju inte direkt den som annars tänker på att betala (eller donera) för mjukvara... Men bara för att jag aldrig* gjort det förut behöver det ju inte betyda att det alltid kommer förbli så. Egentligen borde det vara en naturlig sak för många fler att betala/donera för program. 
*) Inte helt sant, slår det mig nu. En gång var jag med och sponsrade ett kodprojekt till diaspora* och en liten slant har skänkts till Wikipedia.

Sen är ju frågan, om jag skulle börja "göra rätt för mig" till vardags och sponsra utvecklare av mjukvara som jag gillar/har användning av, i vilken ände skulle jag börja? Om vi tittar på just det här med videoströmsparning så är kanske hjälpen jag fått från ffmpeg, att faktiskt spara strömmarna, lite större/viktigare än den hjälp jag (hittills) hunnit få från dig och Privatkopiera då jag bara testat tillägget ett par gånger och sedan fått några några textrader med tips om hur jag själv tar fram strömnamn och ffmpeg-kommandot genom att inspektera infon som webbläsaren har om strömmen. Samtidigt - varför jämföra den exakta nyttan med två olika program - det går väl att donera till båda projekten förstås! Vilket osökt leder mig vidare till tankar om andra mjukvaror/utvecklare som jag haft hjälp av och som jag kanske borde stödja, som t.ex.: Digikam, KeePass, Gimp, BetterJPEG, Advanced JPEG Compressor, VideoLAN, Firefox, Ad Muncher, AdBlock Plus, Greasemonkey, 50 andra Firefox-addons, Windows & Office, GNU/Linux, Open/Libre Office, Notepad++, Datacrow, IrfanView, 7-zip, Drupal, Piriforms många bra program och Steve Gibsons/GRCs program (med exempel som t.ex. SQRL, som snart är redo att ersätta dagens användning av användarnamn/lösenord, eller hur jag för snart 20 år sedan fick hjälp av Steve att rädda en dator som var "förstörd" av CIH-viruset), eller varför inte DC++, utan vilket jag inte hade träffat min fru och bildat familj (och utan barnen hade jag inte suttit här och sparat Pyjamashjältarna från SVT/Barnkanalen :-))...

Oj, det var en bra tankeställare... - jag har verkligen dragit nytta av många program/tjänster/programmerare genom åren - och nästan inte sponsrat/betalat för någonting! *Visst, jag har hjälpt många andra med tjänster/scriptprogrammering utan betalning, även jag...  Men, hmm, det är absolut värt att ta sig en funderare ibland.*

**Comment by Calle-L** [comment]
(Ja just det ja - jag glömde visst att Internet bestämde sig för 10-15 år sedan att ge en annan betydelse till användningen av asterixer runt ord/stycken. Förut indikerade det en tanke/känsla hos den som skrev... och det använde jag mycket ovan, bland mina reflektioner. \*Hatar när det istället skrivs om som italics! Nästan lika frustrerande som när Facebook bestämde sig för att Enter betydde Skicka det halvfärdiga meddelandet istället för Lägg till radbrytning!\*)

**Comment by stefansundin** [comment]
Fixat i v0.1.0.
