### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Lancar223** [stefansundin/privatkopiera#30]
Hej

Får Permission Denied när jag försöker ladda ner https://www.svtplay.se/video/2705548/indiens-dotter
Testade att uppdatera ffmpeg till senaste static, men utan resultat.
[dump.txt](https://github.com/stefansundin/privatkopiera/files/5160897/dump.txt)
vad kan det bero på?

**Comment by stefansundin** [comment]
Hej.

Problemet är nog att du försöker skriva till `C:\`.

Det här varnas mot på hemsidan:
> Obs: Kör inte kommandon från `C:\` (eller `C:\Windows\`). I nya versioner av Windows så kan inte vanliga användare skriva här. Jag rekommenderar att du kör kommandon från ditt skrivbord. För att navigera till skrivbordet, skriv först "`cd Skrivbord`".

Hoppas det löser ditt problem! :)

Mvh Stefan

**Comment by Lancar223** [comment]
ugh! Amatörmiss.
Gamla DOS-dagarna ligger kvar där inget klagade på att man höll på i roten. Kunde väl iofs kört cmd som admin, men inte en tanke på det.

Tack för hjälpen.
