### ISSUE TITLE
Knappen "Bevilja behörigheter" fungerar inte

### ISSUE THREAD

**Issue by morgonte** [stefansundin/privatkopiera#32]
När jag försöker fånga en ström på svtplay får jag fram knappen "Bevilja behörigheter" men det händer inget när jag klickar på den. Länken jag kan kopiera från knappen är "moz-extension://75fe2804-9e72-48d6-9af3-48a88ccbf38a/popup.html#". Jag tänker den vill öppna ett popup-fönster, så jag tar bort inställningen  "Blockera popup-fönster" i Firefox, men får samma resultat. Klistrar jag in länken i ett webbläsarfönster får jag upp en kopia av Privatkopiera's användargränssnitt i fönstret, men där finns förstås ingen ström att fånga, så det går inte att göra något alls.
Firefox 71,0 64 bit. Privatkopiera 0.2.2. Körs på Linux Mint 19.3 MATE 64 bit.

**Comment by stefansundin** [comment]
Hej!

Jag såg inte att du skickade in den här precis innan jag skapade en annan issue med lösningen: https://github.com/stefansundin/privatkopiera/issues/33.

Problemet är att din Firefox version är för gammal. Det fanns en bugg i Firefox innan v75 där popup fönster inte kunde fråga om mer behörigheter. Jag har ändrat versionskravet till v75 så om du besöker https://addons.mozilla.org/en-US/firefox/addon/privatkopiera/ så borde du nu se en varning.

Det finns en workaround men den är lite krånglig. Om du kan uppdatera Firefox på nåt vis så är det bästa lösningen.

**Comment by morgonte** [comment]
Ok. Bäst är att uppdatera. Tack för ditt engagemang! Kanon!
