### ISSUE TITLE
Hur laddar jag ner originalkällan utan någon form av re-encoding/komprimering? 

### ISSUE THREAD

**Issue by deroverda** [stefansundin/privatkopiera#34]
Hej och tack för ett shysst program. Jag håller på att ladda ner från öppetarkiv och undrar hur jag lyckas ladda ner ursprungsformatet och slippa all form av re-encoding etc. 

Med firefox-addonet [The Stream Detector](https://github.com/rowrawer/stream-detector/) får man tillgång till originalkällan (?) vilket visar exempelvis att [Miles Davis](https://www.oppetarkiv.se/video/1194556/miles-davis-pa-stockholms-konserthus?ac=miles%20davl) är .MPD format. Så här ser direktlänken ut:
`https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/dash-avc.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F6354efb1-1e2a-498c-9076-aabb601560cb%2Fdash-avc.mpd`

Dock verkar det som att när jag laddar ner via appen ovan i youtube-dl blir det två separata spår (ljud och bild). 

När jag testar att ladda ner via ditt addon eller addonet jag nämnde ovan får jag olika resultat: .mp4 fil som verkar muxa (eller vad det nu heter) videon och ljudet samt komprimerar alltihopa. Ena gången lyckades audioformatet vara CBR och en annan gång var det VBR. Upplösningen varierade också men det verkar som att 1920x1080 är max. 

Nu vet jag inte varför jag inte hittar denna länk men jag är hundra på att ditt addon eller The Stream Detector även lyckades hitta en url som även innehöll filmen i .TS format. Ursäkta min röriga text. Det enda jag vill är att kunna ladda ner från originalvideon rakt av utan någon som helst "re-encoding"/komprimering.

Jag testade att ladda ner klippet genom ditt addon och välja högsta kvalitet/ström. när jag kör .mp4 filen genom mediainfo får jag fram informationen nedan. Kan det bli bättre än så här eller gör jag någonting fel? All hjälp uppskattas. 

```
General
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1.29 GiB
Duration                                 : 56 min 7 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 298 kb/s
Writing application                      : Lavf58.51.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 56 min 7 s
Bit rate                                 : 3 100 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.060
Stream size                              : 1.22 GiB (94%)
Writing library                          : x264 core 159 r2999 296494a
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=hex / subme=9 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-4 / threads=34 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=6 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=192 / keyint_min=96 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=3100 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=4700 / vbv_bufsize=6200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 56 min 7 s
Bit rate mode                            : Variable
Bit rate                                 : 192 kb/s
Maximum bit rate                         : 196 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 77.1 MiB (6%)
Default                                  : Yes
Alternate group                          : 1
```

**Comment by stefansundin** [comment]
Privatkopiera spottar ur sig:

```
ffmpeg -i "https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Miles Davis på Stockholms konserthus - undefined.mp4"
```

Eftersom kommandot använder `-acodec copy -vcodec copy` så borde ffmpeg kopiera video- och audioströmmarna utan att transcoda eller göra kvalitén sämre. Men du kan ladda ned originalfilerna (samma som ffmpeg gör) på följande sätt:

- Öppna https://www.oppetarkiv.se/video/1194556/miles-davis-pa-stockholms-konserthus
- Klicka på Privatkopiera och klicka på knappen <kbd>Öppna JSON</kbd> som går till https://api.svt.se/videoplayer-api/video/1355934-001OA
- I `videoReferences` så ser du en hel massa olika strömmar i olika format. Jag är osäker på vilken som har bäst kvalité. Privatkopiera använder bara den som har `"format": "hls"` ([kod](https://github.com/stefansundin/privatkopiera/blob/a6646568d8452184f9bf95d95bf8889174129a79/extension/js/svt.js#L49-L51)).
- https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-ts-avc.m3u8
  ```
  #EXTM3U
  #EXT-X-INDEPENDENT-SEGMENTS
  #EXT-X-MEDIA:TYPE=AUDIO,URI="hls-audio-stereo-0/hls-audio-stereo-0.m3u8",GROUP-ID="stereo",LANGUAGE="sv",NAME="Svenska",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
  #EXT-X-STREAM-INF:BANDWIDTH=1577930,AVERAGE-BANDWIDTH=1044636,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.0,AUDIO="stereo",CLOSED-CAPTIONS=NONE,VIDEO-RANGE=SDR
  hls-video-avc-1/hls-video-avc-1.m3u8
  #EXT-X-STREAM-INF:BANDWIDTH=827105,AVERAGE-BANDWIDTH=551901,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=416x234,FRAME-RATE=25.0,AUDIO="stereo",CLOSED-CAPTIONS=NONE,VIDEO-RANGE=SDR
  hls-video-avc-0/hls-video-avc-0.m3u8
  #EXT-X-STREAM-INF:BANDWIDTH=2547305,AVERAGE-BANDWIDTH=1561604,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=25.0,AUDIO="stereo",CLOSED-CAPTIONS=NONE,VIDEO-RANGE=SDR
  hls-video-avc-2/hls-video-avc-2.m3u8
  #EXT-X-STREAM-INF:BANDWIDTH=3856646,AVERAGE-BANDWIDTH=2335158,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.0,AUDIO="stereo",CLOSED-CAPTIONS=NONE,VIDEO-RANGE=SDR
  hls-video-avc-3/hls-video-avc-3.m3u8
  #EXT-X-STREAM-INF:BANDWIDTH=5882738,AVERAGE-BANDWIDTH=3387710,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.0,AUDIO="stereo",CLOSED-CAPTIONS=NONE,VIDEO-RANGE=SDR
  hls-video-avc-4/hls-video-avc-4.m3u8
  #EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-0/hls-video-avc-0-iframe.m3u8",BANDWIDTH=43083,AVERAGE-BANDWIDTH=21654,CODECS="avc1.42c01f",RESOLUTION=416x234,VIDEO-RANGE=SDR
  #EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-1/hls-video-avc-1-iframe.m3u8",BANDWIDTH=108883,AVERAGE-BANDWIDTH=59338,CODECS="avc1.4d401f",RESOLUTION=640x360,VIDEO-RANGE=SDR
  #EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-2/hls-video-avc-2-iframe.m3u8",BANDWIDTH=158625,AVERAGE-BANDWIDTH=89083,CODECS="avc1.4d401f",RESOLUTION=960x540,VIDEO-RANGE=SDR
  #EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-3/hls-video-avc-3-iframe.m3u8",BANDWIDTH=199358,AVERAGE-BANDWIDTH=118215,CODECS="avc1.4d401f",RESOLUTION=1280x720,VIDEO-RANGE=SDR
  #EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-4/hls-video-avc-4-iframe.m3u8",BANDWIDTH=241658,AVERAGE-BANDWIDTH=143475,CODECS="avc1.640029",RESOLUTION=1920x1080,VIDEO-RANGE=SDR
  ```
- Det är filen ovanför som Privatkopiera parsar för att ge användaren möjligheten att välja upplösning. Hitta upplösningen som du vill ha (jag antar den högsta upplösningen).
- Ta `https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/` (sökvägen som innehåller m3u8 filen) plus `hls-video-avc-4/hls-video-avc-4.m3u8`. Detta är samma sökväg som `ffmpeg` kommandot ovan använder.
- https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4.m3u8
  ```
  #EXTM3U
  #EXT-X-VERSION:4
  #EXT-X-PLAYLIST-TYPE:VOD
  #EXT-X-TARGETDURATION:4
  #EXT-X-MEDIA-SEQUENCE:0
  #EXTINF:3.84,
  hls-video-avc-4-1.ts
  #EXTINF:3.84,
  hls-video-avc-4-2.ts
  #EXTINF:3.84,
  hls-video-avc-4-3.ts
  #EXTINF:3.84,
  hls-video-avc-4-4.ts
  
  ... osv
  ```
- Ladda ned alla `.ts` filer.
  - https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4-1.ts
  - https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4-2.ts
  - https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4-3.ts
  - https://svt-vod-7a.akamaized.net/d0/se/20200607/6354efb1-1e2a-498c-9076-aabb601560cb/hls-video-avc-4/hls-video-avc-4-4.ts
  - osv
- konkatenera filerna till en enda fil med något program.
- ???
- Profit!

Hoppas det hjälpte!

**Comment by deroverda** [comment]
Tack så jättemycket för hjälpen Stefan. Trevlig helg.

**Comment by deroverda** [comment]
Tack så jättemycket för hjälpen Stefan. Trevlig helg.
