### ISSUE TITLE
Fel: Den här hemsidan stöds ej.

### ISSUE THREAD

**Issue by BerndtRing** [stefansundin/privatkopiera#35]
Hejsan,

Får ovanstående feltext på alla sidor efter uppgradering av 0.2.2 i Chrome.

**Comment by Bub0** [comment]
Funkar bra här.

**Comment by BerndtRing** [comment]
Så vad gör jag fel?
Har tagit bort den och lagt till igen, samma resultat.
Kan inte lägga till den direkt, får "Misslyckades - Ingen fil", utan måste lägga till den i Programmerarläge.

**Comment by BerndtRing** [comment]
Uppdatering: verkar fungera på TV4 men inte SVT

**Comment by stefansundin** [comment]
Om du högerklickar på Privatkopiera och använder `Inspect Popup` (osäker på vad det är på svenska Chrome) så spottar den ut en del loggar som kanske ger mer insyn i problemet.

Klista gärna in URLer som inte fungerar, det kanske är någon ny URL-struktur på nån del av sidan som jag inte har sett förut. Det var fallet med svtbarn som fixades i v0.2.1.

**Comment by BerndtRing** [comment]
Denna fungerar inte:
https://www.svtplay.se/video/27947351/varldens-samsta-indier/varldens-samsta-indier-sasong-2-avsnitt-6?start=auto

När jag gjorde Inspektera på ovan så fanns det 2 errors, text enlig nedan:

Failed to load resource: net:: ERR_FILE_NOT_FOUND
chrome-extension://ocpimkpebhpoglhecnnccheccacjhdid/css/bootstrap.min.css

Uncaught SyntaxError: Unexpected token function                                                                 svt.js:163 
https://www.svtplay.se/video/27947351/varldens-samsta-indier/varldens-samsta-indier-sasong-2-avsnitt-6?start=auto                                                                                                        popup.js:377 

Ytterligare ett program som inte fungerar, ger samma fel vid Inspektera.
https://www.svtplay.se/video/27995427/det-sitter-i-vaggarna/det-sitter-i-vaggarna-sasong-6-glashuset-i-hammerdals-socken-jamtland

Hoppas det kan vara till nån hjälp.

**Comment by jonas9881** [comment]
kan du fixa så att tilläget klarar av "klipp" även som den gör med "video" i URL:en som denna https://www.svtplay.se/klipp/jMVZAVG/trailer-ellen-hastar-start?info=visa ?

**Comment by stefansundin** [comment]
@jonas9881 Svarade dig i den andra tråden. https://github.com/stefansundin/privatkopiera/issues/78#issuecomment-1328180501

Stänger denna för jag tror det som står här inte är aktuellt längre.
