### ISSUE TITLE
Ladda ner och installera i Chrome?

### ISSUE THREAD

**Issue by e5frog** [stefansundin/privatkopiera#36]
Har försökt flera gånger att ladda ner tillägget (hade en äldre version som jag tog bort). 
Har startat om etc... 
Det går inte attt ladda ner installationsfilen jhjhnecocacdbhlkjgpdacoibidhmgdf_[femsiffrigt nummer].crx
https://chrome.google.com/webstore/detail/privatkopiera/jhjhnecocacdbhlkjgpdacoibidhmgdf

Det står att den är kompatibel med min enhet (Windows/Chrome) så det kan inte vara det som är problemet. 
Finns den att ladda hem någonstans ifrån så man kan installera manuellt i dev-läge?

**Comment by stefansundin** [comment]
Det här är GitHub och det är här koden är lagrad. Jag skrev precis en guide som jag hoppas är enkel att följa: https://github.com/stefansundin/privatkopiera/issues/38
