### ISSUE TITLE
Fungerar inte på Windows XP

### ISSUE THREAD

**Issue by e5frog** [stefansundin/privatkopiera#37]
Lyckades klämma in senaste versionen (0.2.2) med "CRX Downloader/Installer", gick inte att få ner på annat sätt. Fick bara tomma filer från Chrome:s sida. 
Får nu meddelande att "Fel: Den här hemsidan stöds ej."
https://www.svtplay.se/video/12511428/telefonsupporten/telefonsupporten-avsnitt-2?start=auto

Det kanske finns något som _ska_ funka som man kan testa på, annars är det kanske inte Privatkopiera som är problemet. 
För gammal Chrome kanske - även om det står att den är kompatibel. 

0.1.13 hade jag installerad (ja, det var så längesen) - funkade inte heller på svtplay, det var därför jag ville uppgradera.

**Comment by e5frog** [comment]
Installerade 0.1.13 igen, får inget felmeddelande men inte heller någon data.

**Comment by e5frog** [comment]
Uppdatering: 
0.1.13 funkar med denna:
https://www.oppetarkiv.se/video/1953352/kuta-och-kor
0.2.2 däremot ger samma fel "Fel: Hemsidan stöds ej."

**Comment by Bub0** [comment]
> Uppdatering:
> 0.1.13 funkar med denna:
> https://www.oppetarkiv.se/video/1953352/kuta-och-kor
> 0.2.2 däremot ger samma fel "Fel: Hemsidan stöds ej."
> 
> Både 0.1.13 och 0.2.2 funkar med denna:
> https://www.tv4play.se/program/nyheterna/13292657

Funkar bra här i Chrome. Kika

**Comment by Bub0** [comment]
> > Uppdatering:
> > 0.1.13 funkar med denna:
> > https://www.oppetarkiv.se/video/1953352/kuta-och-kor
> > 0.2.2 däremot ger samma fel "Fel: Hemsidan stöds ej."
> > Både 0.1.13 och 0.2.2 funkar med denna:
> > https://www.tv4play.se/program/nyheterna/13292657
> 
> Funkar bra här i Chrome. Kika att du kör senate versionen, installera om eller använd Firefox för det känns som felet är på din sida..

**Comment by stefansundin** [comment]
Vilken Chrome version kör du?

Fungerar bra för mig, får detta kommando:
> ffmpeg -i "https://svt-vod-1e.akamaized.net/d0/world/20191204/90786420-5dfd-4e5e-a5d9-621a2207dcbe/hls-video4/hls-video4.m3u8" -i "https://svt-vod-1e.akamaized.net/d0/world/20191204/90786420-5dfd-4e5e-a5d9-621a2207dcbe/hls-audio0/hls-audio0.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Telefonsupporten - Indien.mp4"

Bra tips från @Bub0, testa med Firefox om du kan.

**Comment by e5frog** [comment]
> 
> 
> Vilken Chrome version kör du?
> 
> Fungerar bra för mig, får detta kommando:
> 
> > ffmpeg -i "https://svt-vod-1e.akamaized.net/d0/world/20191204/90786420-5dfd-4e5e-a5d9-621a2207dcbe/hls-video4/hls-video4.m3u8" -i "https://svt-vod-1e.akamaized.net/d0/world/20191204/90786420-5dfd-4e5e-a5d9-621a2207dcbe/hls-audio0/hls-audio0.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Telefonsupporten - Indien.mp4"
> 
> Bra tips från @Bub0, testa med Firefox om du kan.

**Comment by e5frog** [comment]
Kör man "Inspect" i Chrome 49 så får man fram "svt-vod-1e.akamaized.net/d0/world/20191204/90786420-5dfd-4e5e-a5d9-621a2207dcbe/" under "Sources". 
Ser bara en thumbnail-map där sen, hittar inte "hls-video4/hls-video4.m3u8"-delen
Det finns *vod-1* 2, 4, 7, 8 och 9...

Det är väl sånt här grävande man vill slippa - och istället använda Privatkopiera.

**Comment by stefansundin** [comment]
Ja, om du har en så gammal version så är det nog mycket som inte fungerar. Jag vet tyvärr inte vad den lägsta Chrome-versionen som fungerar är. Du vet nog detta men om du besöker fel webbsida så är det nog ganska stor chans att din dator blir hackad.

Mitt förslag är att testa alternativa program, t.ex.:
- https://svtplay-dl.se/
- https://ytdl-org.github.io/youtube-dl/

**Comment by e5frog** [comment]
Jodå, hackande är man aldrig säker emot.  ;) 

Har kikat lite på de där, vet inte om de är XP-vänliga, men tack ändå. 

Hade varit intressant att prova versioner av Privatkopiera före 0.2.2 och se om någon funkar med det som önskas. Om de finns. 
Blir kanske lättast för alla att bara köra nyare Windows. ;)
Bra valuta för investeringen har det iaf varit, tack.

**Comment by stefansundin** [comment]
> Hade varit intressant att prova versioner av Privatkopiera före 0.2.2 och se om någon funkar med det som önskas. Om de finns.

I v0.2.2 så fixades SVT Play dock, på grund av ändringar på svtplay.se. Men om du vill försöka ladda koden i utvecklingsläge och försöka hitta/fixa problemet så kan du ta en titt på den här: https://github.com/stefansundin/privatkopiera/issues/38

Om jag skulle gissa så beror problemet kanske på att jag har uppdaterat koden att använda lite nyare JavaScript grejer, så som:
- [fetch](https://github.com/stefansundin/privatkopiera/commit/4b110ad72ef66c887f4dd00e9add3d0e561a00c5) ([kräver Chrome 42](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility))
- [async/await](https://github.com/stefansundin/privatkopiera/commit/ad62d93ce206b54b0558fd777d3ca649b6211b44#diff-5d48436fcbe4e2c79becce8e08560e3dR144) ([kräver Chrome 55](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#Browser_compatibility))
- [Array#includes](https://github.com/stefansundin/privatkopiera/commit/6343c5661bde4a83161377dea9d4a65735154784) ([kräver Chrome 47](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility))
- Kanske annat också..

Om din dator är för trög för nyare Windows så kanske du kan fundera på att testa Linux. :)

**Comment by e5frog** [comment]
Tackar för länk och tips. 
Visst hade det varit coolt att göra ett tillägg för Mypal (Pale Moon)?
https://www.mypal-browser.org/
Har gått från Firefox -> Pale Moon -> Mypal. 

Jag är inte alls så hemma på sånt här (har aldrig försökt), är mer van vid Fairchild F8 assembler och har väl fuskat lite för andra CPU:er, lite C, C++, Pascal, Ada, Javscript, html... 

Tror att vi glidit från "Issue #37" men det är väldigt tacksamt att diskutera ämnet.
