### ISSUE TITLE
SVT direktsändningar fungerar inte med v0.2.2

### ISSUE THREAD

**Issue by Lunarwalker60** [stefansundin/privatkopiera#41]
Ibland visas inte program på SVT-Play men då de visas i SVT Direkt på resp kanal har det tidigare att fånga den strömmen med Privatkopiera i Chrome. Det fungerar inte längre sen SVT:s förändringar i slutet av augusti. Är det något som är tänkbart att titta på för dig?

**Comment by stefansundin** [comment]
Jag minns inte när jag senast testade direktsändningar. Borde nog ha testat det innan jag släppte v0.2.2. Ska ta en titt imorgon.

**Comment by Ordval** [comment]
Fantastiskt bra !  

Om det finns några nya live-strömmar utlagda på nätet 
har i alla fall jag inte kunnat hitta några, 
vet å andra sidan inte riktigt var jag skall leta.
De finns ju bland piratsiterna förstås, men då går de
via "leverantören", och är tillfälliga.

**Comment by stefansundin** [comment]
Har nu släppt v0.2.3 vilket fixar direktsändningar.

> Vid ett första påséende kan jag inte se att ändelserna `hls-video-avc-6/hls-video-avc-6.m3u8`
> och `hls-audio-stereo-0/hls-audio-stereo-0.m3u8` sammantaget skulle ge en bättre kvalitet
> än med bara `hls-ts-avc.m3u8`.
> 
> Finns det något särskilt skäl till att du använder de 2 första ?

Om vi tar ett exempel: https://www.svtplay.se/video/28020211/rapport/rapport-29-sep-16-00-2

Först försöker tillägget att ladda metadata och hitta vad det är för video du har öppen. I detta fall så är det: https://api.svt.se/video/j16o345

Där så tar tillägget ut hls strömmen: https://svt-vod-6r.akamaized.net/d0/world/20200929/ce9d158b-72d6-4c37-ab5a-7afbac404bfd/hls-ts-avc.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2Fce9d158b-72d6-4c37-ab5a-7afbac404bfd%2Fhls-ts-avc.m3u8. Den läggs direkt in i listan.

Sedan, för att ge användaren möjligheten att välja kvalité direkt i tillägget, så laddar tillägget ned den här filen och försöker parsa ut de olika alternativen ur m3u8 filen. Till exempel:

```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,URI="hls-audio-stereo-0/hls-audio-stereo-0.m3u8",GROUP-ID="audio-stereo-0",LANGUAGE="sv",NAME="Svenska",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=SUBTITLES,URI="text/text-0.m3u8",GROUP-ID="text",LANGUAGE="sv",NAME="Svenska",DEFAULT=NO,AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound"
#EXT-X-STREAM-INF:BANDWIDTH=1965774,AVERAGE-BANDWIDTH=1741113,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-5/hls-video-avc-5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=287169,AVERAGE-BANDWIDTH=267756,CODECS="avc1.42c015,mp4a.40.2",RESOLUTION=512x288,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-0/hls-video-avc-0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=411484,AVERAGE-BANDWIDTH=378403,CODECS="avc1.42c016,mp4a.40.2",RESOLUTION=512x288,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-1/hls-video-avc-1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=531569,AVERAGE-BANDWIDTH=488919,CODECS="avc1.42c016,mp4a.40.2",RESOLUTION=512x288,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-2/hls-video-avc-2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=749414,AVERAGE-BANDWIDTH=673437,CODECS="avc1.42c016,mp4a.40.2",RESOLUTION=512x288,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-3/hls-video-avc-3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1139044,AVERAGE-BANDWIDTH=1033326,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-4/hls-video-avc-4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3322664,AVERAGE-BANDWIDTH=2882497,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.0,AUDIO="audio-stereo-0",SUBTITLES="text",VIDEO-RANGE=SDR
hls-video-avc-6/hls-video-avc-6.m3u8
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-0/hls-video-avc-0-iframe.m3u8",BANDWIDTH=30315,AVERAGE-BANDWIDTH=13602,CODECS="avc1.42c015",RESOLUTION=512x288,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-1/hls-video-avc-1-iframe.m3u8",BANDWIDTH=41360,AVERAGE-BANDWIDTH=20986,CODECS="avc1.42c016",RESOLUTION=512x288,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-2/hls-video-avc-2-iframe.m3u8",BANDWIDTH=49820,AVERAGE-BANDWIDTH=25265,CODECS="avc1.42c016",RESOLUTION=512x288,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-3/hls-video-avc-3-iframe.m3u8",BANDWIDTH=54990,AVERAGE-BANDWIDTH=31112,CODECS="avc1.42c016",RESOLUTION=512x288,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-4/hls-video-avc-4-iframe.m3u8",BANDWIDTH=89300,AVERAGE-BANDWIDTH=51000,CODECS="avc1.4d401e",RESOLUTION=768x432,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-5/hls-video-avc-5-iframe.m3u8",BANDWIDTH=186825,AVERAGE-BANDWIDTH=90786,CODECS="avc1.4d401f",RESOLUTION=1280x720,VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:URI="hls-video-avc-6/hls-video-avc-6-iframe.m3u8",BANDWIDTH=186825,AVERAGE-BANDWIDTH=116805,CODECS="avc1.4d401f",RESOLUTION=1280x720,VIDEO-RANGE=SDR
```

Så det är här alternativen med olika upplösningar och bitrate kommer från.

Du har rätt att översta alternativet med den högsta upplösningen ger samma resultat som att använda `hls-ts-avc.m3u8`. Jag tror inte att jag har hävdat att det ger bättre resultat eller högre kvalité.

**Comment by Ordval** [comment]
Valbarhet, vilket är bra,
...från "TV4ever" är jag van vid bara 1 kvalité.
Deras program går just nu bet på Svt.
