### ISSUE TITLE
Fick inga undertexter vid nedladdning

### ISSUE THREAD

**Issue by RogerGustavsson** [stefansundin/privatkopiera#43]
Laddade några filer från SVTPlay men någon undertext kom inte med. Gör jag något fel?

Roger

**Comment by Bub0** [comment]
Välj undertexter i rullgardinen "ström" i privatkopiera. 
Annars brukar SVT ha hårdkodad sv text i sina publikationer. :-)

**Comment by RogerGustavsson** [comment]
Tack! 
Finns det något trix eller måste man ta textfilen separat? 
Markerade största filen, 4.29 GiB, den blev bara 2.44 GiB.

![dropdown](https://user-images.githubusercontent.com/28738553/94580402-2a11b000-027a-11eb-892f-f32472ddb858.jpg)

**Comment by Bub0** [comment]
Separat, storleken är en gissning baserad på bitrate antar jag, men jo filerna blir mindre än vad det står i tillägget. Kolla att du fått med ljudet också, vet att det bara kom med ljud när man valde master.m3u8 eller ts-avc.m3u8 tidigare.

**Comment by RogerGustavsson** [comment]
Jodå, ljud är det också och texten kommer också med. Lite pill jämfört med det program jag använt tidigare (youtube-gl) men det slutade fungera på SVTPlay i augusti.

**Comment by stefansundin** [comment]
> Finns det något trix eller måste man ta textfilen separat?

Just nu så finns det inte något alternativ att muxa in undertexterna direkt. Jag hoppas att jag kan bygga in det i någon framtida version.

Det går att jobba runt nu genom att klippa och klistra lite med kommandot. Exempel med https://www.svtplay.se/video/26160720

Ta din videoström:
> ffmpeg -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "En enkel till Antibes - En enkel till Antibes.mp4"

Ta sedan undertexterna:
> ffmpeg -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/text/text-0.vtt" "En enkel till Antibes - En enkel till Antibes.srt"

Kopiera `-i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/text/text-0.vtt"` och klistra in det som en tredje input:
> ffmpeg -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -i "https://svt-vod-10c.akamaized.net/d0/se/20200921/9154ad0f-e8c1-44e7-b262-51b551520c03/text/text-0.vtt" -acodec copy -vcodec copy -absf aac_adtstoasc "En enkel till Antibes - En enkel till Antibes.mp4"

Förhoppningsvis blir det en bättre upplevelse i en framtida version! :)

**Comment by stefansundin** [comment]
> Markerade största filen, 4.29 GiB, den blev bara 2.44 GiB.

Filstorleken är en gissning. Jag borde uppdatera koden, eller kanske ta bort det om det inte går att räkna ut på ett bra sätt längre.

**Comment by Lunarwalker60** [comment]
Apropå undertexter: TV4 Play ändrades också för en tid sen men jag la en issue hos SVTPLAY-DL och det är fixat i version 2.6
Exempel: för text från TV4 Play 
svtplay-dl -f -o "G:\Download\TV Play\Johan Falk del 1 - Spelets regler" -S --force-subtitle "https://www.tv4play.se/program/Johan/12520851"
Föredrar att ta videoströmmen med Privatkopiera eftersom det är mycket effektivare.

**Comment by stefansundin** [comment]
Har precis släppt v0.3.0 och nu inkluderas undertexter automatiskt. De finns inte längre att välja i menyn. Jag funderat en hel del vad som var bästa sättet att inkludera dem, men jag kom fram till att det är nog bäst att alltid ta med dem. Om du inte vill ha med dem så kan du radera den inputen från kommandot (vilket är enklare nu när kommandot är en textruta som du kan förstora), eller bara välja bort dem när du spelar upp din video.

**Comment by RogerGustavsson** [comment]
Tack! Man har vant sig vid undertexter på nästan allt.

Roger

Den tis 5 jan. 2021 kl 08:37 skrev Stefan Sundin <notifications@github.com>:
