### ISSUE TITLE
Får ingen dataström på UR Play

### ISSUE THREAD

**Issue by perbosson** [stefansundin/privatkopiera#44]

**Comment by gugge59** [comment]
Får ingen dataström, har urplay.se bytt till JWplayer? Javascript video player?

**Comment by stefansundin** [comment]
Fixat i v0.2.4 som nyss släppts. f42cf98bbe703039d3e90c69e52e8e0fc3f452d6

**Comment by animationista** [comment]
Funkar ej i 0.3.6 (chrome på android)

**Comment by Bub0** [comment]
Testade i Kiwi browser och det funkar inte för mig heller. "Fel: Den här hemsidan stöds ej".Men antar att tillägget inte är anpassat för smartphones etc och vet inte om det är en bugg.egentligen.. Funkar fint i Firefox och chrome på datorn. :-)
