### ISSUE TITLE
SVT Direkt

### ISSUE THREAD

**Issue by Lunarwalker60** [stefansundin/privatkopiera#48]
Hej

Alla olika upplösningsalternativ ger samma ffmpeg-kommando. Onödigt hög för de flesta program.

**Comment by Lunarwalker60** [comment]
Sorry - bortse från detta. Fick nyss ett klipp med lägsta upplösning.

**Comment by Bub0** [comment]
Om du tar master eller hls-ts kan du välja kvalitet själv. ;-)

Den tors 17 dec. 2020 20:35Lunarwalker60 <notifications@github.com> skrev:

**Comment by Lunarwalker60** [comment]
Det var jag själv som klantade. Funkar alldeles utmärkt när man vet hur man skall göra.
![image](https://user-images.githubusercontent.com/61702762/102943544-afdb7b00-44b8-11eb-9b04-37fb4404e095.png)
