### ISSUE TITLE
Svtplay Octonauterna

### ISSUE THREAD

**Issue by Meeto1** [stefansundin/privatkopiera#5]
Hej Stefan.
Tack för ett fint program :)
Ville ta ner serien Octonauterna men de gick inte :/
Här är länken:

ffmpeg -i "https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Octonauterna - Odjurskartan.mp4" 

Fungerade fint med ett annat barnprogram men här blev de stop?

Testade även Biet Maya, varav den första gick men inte de andra:

ffmpeg -i "https://svtplay10s-f.akamaihd.net/i/se/open/20171019/1318830-055A/PG-1318830-055A-MAYATHEBEEDI-01.dif_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Biet Maya - Avsnitt 55.mp4"

ffmpeg -i "https://svtplay15k-f.akamaihd.net/i/se/open/20171020/1318830-056A/PG-1318830-056A-MAYATHEBEEDI-01.dif_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Biet Maya - Avsnitt 56.mp4"

På de andra dök denna text upp i cmd:

E:\>ffmpeg -i "https://svtplay15k-f.akamaihd.net/i/se/open/20171020/1318830-056A/PG-1318830-056A-MAYATHEBEEDI-01.dif_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8" -acodec copy -vcodec copy -absf aac_adtstoasc "Biet Maya - Avsnitt 56.mp4"
ffmpeg version N-88042-g72c3d9ae45 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  0.100 / 58.  0.100
  libavformat    58.  0.100 / 58.  0.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.100 /  7.  0.100
  libswscale      5.  0.100 /  5.  0.100
  libswresample   3.  0.100 /  3.  0.100
  libpostproc    55.  0.100 / 55.  0.100

Sen hände där inget mer :/

Tack på förhand//

**Comment by stefansundin** [comment]
Hej!

Jag misstänker att detta är en bugg i ffmpeg. Den lyckas ladda ned m3u8 filen, men sen tar det stopp. Jag lyckades komma vidare genom att först ladda ned m3u8 filen manuellt, och sedan peka ffmpeg på den lokala filen.

Så testa följande:

```
curl -o index_6_av.m3u8 "https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8"

ffmpeg -protocol_whitelist file,http,https,tcp,tls,httpproxy -i index_6_av.m3u8 "Octonauterna - Odjurskartan.mp4"
```

Jag testade bara den första, så säg till om detta inte fungerar på alla.

Du skulle också kunna testa gamla versioner av ffmpeg och se om de fungerar bättre.

**Comment by Meeto1** [comment]
Stort tack till ditt engagemang, ska testa i helgen :)
Mvh Micke "Metoo1"

Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Stefan Sundin <notifications@github.com> Datum: 2017-10-28  20:17  (GMT+01:00) Till: stefansundin/privatkopiera <privatkopiera@noreply.github.com> Kopia: Meeto1 <ekcim82@gmail.com>, Author <author@noreply.github.com> Rubrik: Re: [stefansundin/privatkopiera] Svtplay Octonauterna (#5) 
Hej!
Jag misstänker att detta är en bugg i ffmpeg. Den lyckas ladda ned m3u8 filen, men sen tar det stopp. Jag lyckades komma vidare genom att först ladda ned m3u8 filen manuellt, och sedan peka ffmpeg på den lokala filen.
Så testa följande:
curl -o index_6_av.m3u8 "https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8"

ffmpeg -protocol_whitelist file,http,https,tcp,tls,httpproxy -i index_6_av.m3u8 "Octonauterna - Odjurskartan.mp4"

Jag testade bara den första, så säg till om detta inte fungerar på alla.
Du skulle också kunna testa gamla versioner av ffmpeg och se om de fungerar bättre.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stefansundin/privatkopiera","title":"stefansundin/privatkopiera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stefansundin/privatkopiera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stefansundin in #5: Hej!\r\n\r\nJag misstänker att detta är en bugg i ffmpeg. Den lyckas ladda ned m3u8 filen, men sen tar det stopp. Jag lyckades komma vidare genom att först ladda ned m3u8 filen manuellt, och sedan peka ffmpeg på den lokala filen.\r\n\r\nSå testa följande:\r\n\r\n```\r\ncurl -o index_6_av.m3u8 \"https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8\"\r\n\r\nffmpeg -protocol_whitelist file,http,https,tcp,tls,httpproxy -i index_6_av.m3u8 \"Octonauterna - Odjurskartan.mp4\"\r\n```\r\n\r\nJag testade bara den första, så säg till om detta inte fungerar på alla.\r\n\r\nDu skulle också kunna testa gamla versioner av ffmpeg och se om de fungerar bättre."}],"action":{"name":"View Issue","url":"https://github.com/stefansundin/privatkopiera/issues/5#issuecomment-340210053"}}}

**Comment by Meeto1** [comment]
Du hade rätt, fungerade fint med en äldre utgåva. Tack igen för fin support!Mvh Micke


Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Stefan Sundin <notifications@github.com> Datum: 2017-10-28  20:17  (GMT+01:00) Till: stefansundin/privatkopiera <privatkopiera@noreply.github.com> Kopia: Meeto1 <ekcim82@gmail.com>, Author <author@noreply.github.com> Rubrik: Re: [stefansundin/privatkopiera] Svtplay Octonauterna (#5) 
Hej!
Jag misstänker att detta är en bugg i ffmpeg. Den lyckas ladda ned m3u8 filen, men sen tar det stopp. Jag lyckades komma vidare genom att först ladda ned m3u8 filen manuellt, och sedan peka ffmpeg på den lokala filen.
Så testa följande:
curl -o index_6_av.m3u8 "https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8"

ffmpeg -protocol_whitelist file,http,https,tcp,tls,httpproxy -i index_6_av.m3u8 "Octonauterna - Odjurskartan.mp4"

Jag testade bara den första, så säg till om detta inte fungerar på alla.
Du skulle också kunna testa gamla versioner av ffmpeg och se om de fungerar bättre.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stefansundin/privatkopiera","title":"stefansundin/privatkopiera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stefansundin/privatkopiera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stefansundin in #5: Hej!\r\n\r\nJag misstänker att detta är en bugg i ffmpeg. Den lyckas ladda ned m3u8 filen, men sen tar det stopp. Jag lyckades komma vidare genom att först ladda ned m3u8 filen manuellt, och sedan peka ffmpeg på den lokala filen.\r\n\r\nSå testa följande:\r\n\r\n```\r\ncurl -o index_6_av.m3u8 \"https://svtplay2r-f.akamaihd.net/i/se/open/20170921/1374573-001A/PG-1374573-001A-THEOCTONAUTS-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8\"\r\n\r\nffmpeg -protocol_whitelist file,http,https,tcp,tls,httpproxy -i index_6_av.m3u8 \"Octonauterna - Odjurskartan.mp4\"\r\n```\r\n\r\nJag testade bara den första, så säg till om detta inte fungerar på alla.\r\n\r\nDu skulle också kunna testa gamla versioner av ffmpeg och se om de fungerar bättre."}],"action":{"name":"View Issue","url":"https://github.com/stefansundin/privatkopiera/issues/5#issuecomment-340210053"}}}

**Comment by stefansundin** [comment]
@Meeto1 Kan du meddela vilken version som fungerar ifall fler har samma problem? Tack!

**Comment by Meeto1** [comment]
Denna versionen vart de som fungerade:
FFmpeg version: 20170130-cba4f0e
FFmpeg win64
