### ISSUE TITLE
SVTplay: Unable to find a suitable output format for 'pipe:'

### ISSUE THREAD

**Issue by pheldda** [stefansundin/privatkopiera#52]
Vissa kommandon som Privatkopiera skapar på SVT play, innehåller ett extra citattecken som gör att ffmpg genererar ett fel: 
Unable to find a suitable output format for 'pipe:'

Exempel på https://www.svtplay.se/video/29402400/mud?start=auto
blir det
`ffmpeg -i "https://svt-vod-secure-2c.akamaized.net/d0/secure/20201219/49c8e7e5-635c-401a-90bb-cdff527a497d/hls-video-avc-4/hls-video-avc-4.m3u8?aka_me_session_id=AAAAAAAAAAAJ3O1fAAAAAIkP7HBI9vTgkGFAmoTX4iqwphi7g7Cy3SVjEdQaSZhE%2fuzZESI9rZ%2ftM7K58SZrcFm8hKoBNq5K" -i "https://svt-vod-secure-2c.akamaized.net/d0/secure/20201219/49c8e7e5-635c-401a-90bb-cdff527a497d/"hls-audio-stereo-1/hls-audio-stereo-1.m3u8?aka_me_session_id" -acodec copy -vcodec copy -absf aac_adtstoasc "Mud - Mud.mp4"`

dvs tecknet efter första snedstreck
...`/"hls-audio-stereo-1/`...

Använde Chrome och Privatkopiera v 0.2.4

**Comment by pheldda** [comment]
Det var en split som inte tog hänsyn till att det kan finnas fler '=' i strängen.

Potentiell fix:

diff --git a/extension/js/popup.js b/extension/js/popup.js
index 86334de..cc80a55 100644
--- a/extension/js/popup.js
+++ b/extension/js/popup.js
@@ -252,7 +252,7 @@ function master_callback(length, fn, base_url) {
         var args = line.substring(line.indexOf(":")+1).match(/[A-Z\-]+=(?:"[^"]*"|[^,]*)/g);
         if (!args) return
         var obj = toObject(args.map(function(arg) {
-          var kv = arg.split("=")
+          var kv = arg.split(/=(.*)/)
           if (kv[1].startsWith('"') && kv[1].endsWith('"')) {
             kv[1] = kv[1].substring(1, kv[1].length-1)
           }

**Comment by stefansundin** [comment]
Hej! Ursäkta att jag är lite sen till tråden.

Fin upptäck. Tack för rapporten!

Ja, den där koden är inte den bästa jag har skrivit. Jag valde att fixa det på detta vis: 5767a6586868b3745c048cb8ef4b2b6702bce7a8

https://github.com/stefansundin/privatkopiera/blob/5767a6586868b3745c048cb8ef4b2b6702bce7a8/extension/js/popup.js#L254-L261

Det är lite underligt att den här konstiga `aka_me_session_id` parametern inte finns på andra videoklipp.

En workaround i dessa fall är att försöka med originalfilen (`hls-ts-avc.m3u8`, nederst i menyn). Då kommer man runt eventuella buggar i den här delen av koden.

Jag ska försöka släppa en ny version med fixen snart, kanske ikväll eller imorgon.

Tack igen!

**Comment by pheldda** [comment]
Hej! Ja workaround fungerade bra, tackar!
Hittar inga fler `aka_me_session_id `just nu heller. Fick en på julafton på en liveström dock.

**Comment by stefansundin** [comment]
Har släppt v0.3.0 nu med den här fixen.
