### ISSUE TITLE
Ingen undertext?

### ISSUE THREAD

**Issue by Jallet1** [stefansundin/privatkopiera#56]
Hejsan

"Undertexter inkluderas automatiskt. De finns inte i listan längre."

Så står det efter uppdateringen men jag kan inte hitta undertexter nu om jag exempelvis tar hem en video från Play. Brukar alltid kolla i VLC Player men när jag högerklickar och väljer Undertext finns det inga Underspår där med undertexter. 

Vad beror detta på? Hur ska man gå tillväga?

**Comment by stefansundin** [comment]
Hej.

Det är många fall där undertexter inte stöds än. Allt den här uppdatering gjorde var att automatiskt inkludera undertexterna i de fallen som de redan stöds. T.ex. så fungerar det inte på live-sändningar. Jag har hittat vart undertexterna finns men tyvärr så verkar ffmpeg inte klara av dem särskilt bra så det är därför jag inte har kodat så att de inkluderas i kommandot.

Tyvärr så kan jag inte förklara varför ditt specifika fall inte fungerar då du inte har länkat programmet som du har problem med.

**Comment by Jallet1** [comment]
Testade tidigare i dag med dessa tre men ingen undertext följde med. 

https://www.svtplay.se/video/29487460/vader/vader-7-jan-09-45
https://www.svtplay.se/video/29521420/sportnytt/sportnytt-i-morgonstudion-7-jan-09-16
https://www.svtplay.se/video/29546972/allsang-pa-skansen/allsang-pa-skansen-sommaren-2020-avsnitt-1'

Nu under kvällen är det samma grej med dessa som jag testade.
https://www.svtplay.se/video/2911876/arkitekturens-parlor/arkitekturens-parlor-sasong-2-avsnitt-31
https://www.svtplay.se/video/29438424/darin-live-fran-globen

Eller finns det några det funkar med? Detta måste verkligen åtgärdas.

**Comment by stefansundin** [comment]
> Detta måste verkligen åtgärdas.

Or else?

Seriöst dock.. du kan ju inte vänta dig att allt är buggfritt, speciellt då det är ett gratis program. Skulle uppskatta bättre ton.

För att åtgärda problemet så får du ändra filändelsen på utfilen från `.mp4` till `.mkv`.

**Comment by Jallet1** [comment]
Or else saknas en funktion som bör finnas där. Detta har ju funnits länge innan så lite märkligt med en uppdatering där det försvinner.

Testade att byta filändelse på Allsången men det blev ingen skillnad. Dvs ingen undertext.

**Comment by Lunarwalker60** [comment]
ffmpeg lagrar inte in undertexter i mp4 - då måste man ha mkv eller annat format som kan lagra in texter.
För att få texter nu från SVT får man ändra lite på kommandot, tex:

ffmpeg -i "https://svt-vod-1t.akamaized.net/d0/se/20201230/94f672cb-3845-4067-bedf-f726b24bfbc9/hls-video-avc-1/hls-video-avc-1.m3u8" -i "https://svt-vod-1t.akamaized.net/d0/se/20201230/94f672cb-3845-4067-bedf-f726b24bfbc9/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -i "https://svt-vod-1t.akamaized.net/d0/se/20201230/94f672cb-3845-4067-bedf-f726b24bfbc9/text/text-0.m3u8" -acodec copy -vcodec copy "snabba-cash.mp4" -absf aac_adtstoasc "snabba-cash.srt"

**Comment by Belzid** [comment]
Det går ju att få in texten i mp4 formatet också om man lägger till parametern -scodec mov_text
