### ISSUE TITLE
URplay stopped working

### ISSUE THREAD

**Issue by erdzeichen** [stefansundin/privatkopiera#58]
Hej, great program thank you.
these videos did not show a link. It said working.....
https://urplay.se/program/200497-dolda-kameran-i-naturen-i-skogen
https://urplay.se/serie/205473-perspektiv-pa-varlden
https://urplay.se/serie/213087-murar-granser-och-taggtrad
https://urplay.se/serie/203240-samernas-tid

**Comment by stefansundin** [comment]
Fixat i v0.3.2.
