### ISSUE TITLE
Tv4 api

### ISSUE THREAD

**Issue by ArashShiri** [stefansundin/privatkopiera#6]
Om vi hämtar data från https://prima.tv4play.se/api/web/asset/${video_id}/play.json?protocol=HLS3,  och parsar denna som json så får man ut en Hls ström istället vilket känns smidigare och mer universalt. 

ex https://prima.tv4play.se/api/web/asset/3349622/play.json?protocol=HLS3

**Comment by stefansundin** [comment]
Utmärkt. Tackar!

**Comment by stefansundin** [comment]
v0.1.2 har släppts med detta.
