### ISSUE TITLE
UR Play funkar inte...

### ISSUE THREAD

**Issue by MatteusGitHub** [stefansundin/privatkopiera#61]
Hej Stefan!
Jag har använt Privatkopiera i Chrome ett tag och jag gillar det verkligen!
Det funkar hur bra som helst på SVTPlay, men tyvärr så funkar det inte att ladda ner någonting från UR Play.
Den bara säger "Laddar, Var god vänta" i all evighet.
Privatkopiera är väldigt bra, men snälla fixa detta i uppdatering 0.3.2.

**Comment by stefansundin** [comment]
Fixat i v0.3.2.
