### ISSUE TITLE
Avsnitt som har " med i sin titel kan ej sparas ner 

### ISSUE THREAD

**Issue by mippen** [stefansundin/privatkopiera#62]
Om man kör kommando där titeln har " med i sitt namn så klarar systemet ej att spara filen.

ffmpeg -i "https://lbs-usp-hls-vod.cmore.se/vod/27a2e/20g5dxwzcd1(13314191_ISMUSP).ism/20g5dxwzcd1(13314191_ISMUSP).m3u8?hls_no_audio_only=true" -vcodec copy -acodec copy "Helen Sjöholm om kvällens gala- "En euforisk kvall".mkv"

men om man ändrar till "Helen Sjöholm om kvällens gala- En euforisk kvall.mkv" fungerar det fint

**Comment by stefansundin** [comment]
Hej. Tror det är den här videon du försöker ladda ned? https://www.tv4play.se/program/efter-fem/helen-sj%C3%B6holm-om-kv%C3%A4llens-gala-en-euforisk-kv%C3%A4ll/13314191

För mig är filnamnet `Helen Sjöholm om kvällens gala- ”En euforisk kväll”.mkv`, dvs det sånna där sneda citationstecken. Försökte du ändra till "vanliga" citationstecken? I det fallet så borde texten i fältet bli röd, något som är tänkt att påpeka att det är tecken där som kanske inte är så bra.

Jag ändrade nästan så att citationstecken ersätts med `\"`, men sedan kom jag ihåg att det tyvärr inte fungerar exakt likadant i Linux och Windows, och just nu går det inte att välja i Privatkopiera vilken kommandotolk man använder.

Jag har inte testat i Windows. Ersätter kanske cmd alla `”` med `"` automatiskt när man klistrar in?

**Comment by mippen** [comment]
För mig var det "dubbla" citationstecken..  "Helen Sjöholm om kvällens gala- "En euforisk kvall".mkv"
Dvs filnamnet hade citationstecken i sitt namn.
Osäker på om det ersätter med ngt.

**Comment by stefansundin** [comment]
Har nu släppt v0.3.5 där detta hanteras genom att en hel drös olika citationstecken (`"”´‘’`) nu ersätts med ett enkelt citationstecken (`'`). 54e05d7230b292c4738a3e0ebc242045ee541770

Tack för rapporten @mippen.

https://github.com/stefansundin/privatkopiera/blob/679527615c33aab32502b09f07cc978376009df3/extension/js/popup.js#L99
