### ISSUE TITLE
SVT Play v0.3.2

### ISSUE THREAD

**Issue by Maltavius** [stefansundin/privatkopiera#67]
Har försökt med olika avsnitt av Thunderbirds från SVT play både i Firefox och i Chrome
https://www.svtplay.se/video/16526586/thunderbirds/thunderbirds-sasong-2-avsnitt-4?start=auto

![image](https://user-images.githubusercontent.com/10133945/106750059-9e44d180-6627-11eb-9b76-c44953d21091.png)

**Comment by partviska** [comment]
Har samma problem här med länk
https://www.svtplay.se/video/29997666/uppdrag-granskning/uppdrag-granskning-stockholms-ensammaste-man

**Comment by MrsYoyo** [comment]
Samma problem för mig, verkar vara alla länkar från svtplay

**Comment by Lunarwalker60** [comment]
Testa denna för UG

ffmpeg -y -i "https://svt-vod-7p.akamaized.net/d0/world/20210202/3caa9366-d211-49b8-9d13-86a3794c5081/cmaf-video-avc-1/cmaf-video-avc-1.m3u8" -i "https://svt-vod-7p.akamaized.net/d0/world/20210202/3caa9366-d211-49b8-9d13-86a3794c5081/cmaf-audio-stereo-1/cmaf-audio-stereo-1.m3u8" -i "https://svt-vod-7p.akamaized.net/d0/world/20210202/3caa9366-d211-49b8-9d13-86a3794c5081/text/text-0.m3u8" -c:v copy -c:a copy  "Uppdrag granskning - E04 - Stockholms ensammaste man¿.mkv"

**Comment by Lunarwalker60** [comment]
Testa denna för Thunderbirds

ffmpeg -y -i "https://svt-vod-1k.akamaized.net/d0/se/20210119/2f539554-40a1-4b91-bbb5-d5f4f4549f4d/hls-video-avc-1/hls-video-avc-1.m3u8" -i "https://svt-vod-1k.akamaized.net/d0/se/20210119/2f539554-40a1-4b91-bbb5-d5f4f4549f4d/hls-audio-stereo-1/hls-audio-stereo-1.m3u8" -i "https://svt-vod-1k.akamaized.net/d0/se/20210119/2f539554-40a1-4b91-bbb5-d5f4f4549f4d/text/text-0.m3u8" -c:v copy -c:a copy  "Thunderbirds - S02E04 - Staden på havets botten.mkv"

**Comment by stefansundin** [comment]
Fixat i v0.3.3. 7e6430957235ece6149273e412ac495a8ddf18bd

Skulle vara trevligt om de slutar pilla på sidan eller om de kunde ge oss ett enklare sätt att få fram `videoSvtId` från id numret i URLen. Man börjar ju fundera på om det är någon sorts baseXX-kodning av samma nummer. Försökte gräva lite i JavaScriptet men lyckades inte hitta något tyvärr.
