### ISSUE TITLE
SVTPlay

### ISSUE THREAD

**Issue by smartinf** [stefansundin/privatkopiera#68]
The privatkopiera (ver 0.3.2) addon  doesn't work any more. Gives no command. Just says:
Filnamn:  Filnamn.mkv
Kommando: ffmpeg...

On the last line says:  Laddar, var god vänta

I have tested with Chrome and Firefox on windows and Linux. With the same result

**Comment by MrsYoyo** [comment]
Same problem for me!

**Comment by Lunarwalker60** [comment]
SVT har ändrat sammansättningen av informationen i HTML.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2021-02-03, 23:12 MrsYoyo <notifications@github.com> wrote:

   
  Same problem for me!

**Comment by stefansundin** [comment]
Fixat i v0.3.3. Titta helst i listan innan du skickar in en rapport, detta rapporterades först i #67.
