### ISSUE TITLE
SVT Play 0.3.2

### ISSUE THREAD

**Issue by MrsYoyo** [stefansundin/privatkopiera#69]
Testat olika videos på SVT play men får samma meddelande, Laddar var god vänta. Det kommer aldrig fram något kommando att kopiera. 

Ex på video: https://www.svtplay.se/video/29403084/en-karlekshistoria?start=auto
https://www.svtplay.se/video/13942344/abba-dabba-dooo/det-var-da-i-tv2-abba-dabba-dooo?start=auto

**Comment by Lunarwalker60** [comment]
Testa denna för ABBA

ffmpeg -y -i "https://svt-vod-5h.akamaized.net/d0/se/20200517/05035c42-ac45-4f7f-942b-f37f2b0b67d1/
hls-video-avc-1/hls-video-avc-1.m3u8" -i "https://svt-vod-5h.akamaized.net/d0/se/20200517/05035c42-ac45-4f7f-942b-f37f2b0b67d1/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -c:v copy -c:a copy  "ABBA-dabba-dooo!! - S01E04.mkv"

**Comment by stefansundin** [comment]
Fixat i v0.3.3. Titta helst i listan innan du skickar in en rapport, detta rapporterades först i #67.
