### ISSUE TITLE
SVTPLAY

### ISSUE THREAD

**Issue by MeSwede** [stefansundin/privatkopiera#71]
Hej!

Jag har precis börjat experimentera med ditt program via FireFox...

Hur får man igång nedladdningen?

Tack igen!

MeSwede

**Comment by Bub0** [comment]
Det står ju... Du behöver ffmpeg. Går att använda andra program som laddar ner med ffmpeg också, tex Allavsoft & ChrisPC.

**Comment by MeSwede** [comment]
...plugin fixar ffmpeg. Sedan öppnar jag TERMINAL på min Macintosh (MacBook Pro) och kopierar in texten... Inget händer - säkerligen ett mesförstånd! Tack igen för hjälp!

**Comment by MeSwede** [comment]
I övrig körs Mac OS (inte Windows)! 

MeSwede

**Comment by MeSwede** [comment]
Jag har ffmpeg och kör Mac OS (inte Linux eller Windows)... Inget händer efter att ha klistrat in i "terminalen" - borde väl hamna i Downloads-mappen?

Tack igen!

MeSwede

**Comment by stefansundin** [comment]
Det hamnar i mappen du "är i" i terminalen. Om du inte har navigerat till en annan mapp så hamnar de nog i din hemmapp. Du kan köra `pwd` för att få den att skriva ut sökvägen till mappen.

**Comment by MeSwede** [comment]
FELMEDDELANDE sedan någon dag tillbaka...

"Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)"

...updates?

Tack på förhand!

MeSwede

**Comment by stefansundin** [comment]
Nu är det ffmpeg vi snackar om antar jag?`Jag har inte fått det där meddelandet personligen. Det låter som en varning och inte ett fel. Fortsätter ffmpeg att jobba? Om det fortsätter så är det nog bara att ha tålamod.

Testa följa tipsen här: https://video.stackexchange.com/questions/25643/ffmpeg-thread-queue-size-warning-what-does-this-mean

**Comment by MeSwede** [comment]
...nej - kommer på slutet - i alla fall om man laddar ner AKTUELLT eller RAPPORT - prövar under kvällen på annat. Och då sparas inget (ingen fil skapas i "Downloads").

**Comment by MeSwede** [comment]
...nej - kommer på slutet - i alla fall om man laddar ner AKTUELLT eller RAPPORT - prövar under kvällen på annat. Och då sparas inget (ingen fil skapas i "Downloads").

**Comment by MeSwede** [comment]
Same meddelande ikväll...

"Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)"

...what now?

Tack igen!

MeSwede

**Comment by Maltavius** [comment]
Det enda jag hittar om det där meddelandet är att din dator är för slö för att orka med att encoda i realtid.
