### ISSUE TITLE
Privatkopiera - SVTPlay - Mac OS

### ISSUE THREAD

**Issue by MeSwede** [stefansundin/privatkopiera#73]
Hej!

Jag kan "privatkopiera" ladda ner AUDIO-CLIP och VIDEO-clip separat...

ffmpeg -i "https://svt-vod-6d.akamaized.net/d0/world/20210111/814afb5e-f8d9-4d76-873c-d303755b5579/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-6d.akamaized.net/d0/world/20210111/814afb5e-f8d9-4d76-873c-d303755b5579/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -vcodec copy -acodec copy "Nyhetsflödet - Pandemilagen på 60 sekunder.mkv"

Vore ju trevligt att få en fil, .mkv till exempel! Eller .mp4!

Tacksam för hjälp!

MeSwede

**Comment by stefansundin** [comment]
Det där kommandot som du har där fungerar ju perfekt. Det gör ju exakt det du vill. Vad är det som inte fungerar?

**Comment by MeSwede** [comment]
...kommandot kommer från din FIREFOX-PlugIn - tack!

Dock, verkar inte ha förstått hur filen eller filerna fås ner...

Vad skall skrivas in i TERMINAL på Mac OS... Prövade med ett downloadprogram - MVRP (Mac VideoRipper Pro by DVDSuki Software Inc) - som fungerat tidigare på SVT, dock inte längre. MVRP tar dock emot filerna från kommandot, dock separat - Audio och Video separat.

Sorry for being lost!

Tacksam för hjälp - lösningen kan inte vara långt borta!

MeSwede

**Comment by Bub0** [comment]
Gissar att lösningen är ffmpeg.

**Comment by stefansundin** [comment]
@MeSwede Ja, du måste installera ffmpeg. Det här är förklarat på hemsidan: https://stefansundin.github.io/privatkopiera/#ffmpeg

För Mac så är det enklast att ladda ned här: https://evermeet.cx/ffmpeg/. Här är direktlänk: https://evermeet.cx/ffmpeg/ffmpeg-4.3.1.7z

Efter att du extraherat 7z filen så får du en fil som bara heter ffmpeg. Du måste köra den från terminalen. Om du lämnar ffmpeg filen i Downloads-mappen så måste du först navigera in till den mappen genom att köra `cd Downloads`. Om du väljer att inte lägga ffmpeg i PATH så måste du skriva `./` före kommandot.

Det vill säga, du vill nog köra följande kommandon efter att du öppnat Terminalen:

```
cd Downloads
./ffmpeg -i "https://svt-vod-6d.akamaized.net/d0/world/20210111/814afb5e-f8d9-4d76-873c-d303755b5579/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-6d.akamaized.net/d0/world/20210111/814afb5e-f8d9-4d76-873c-d303755b5579/hls-audio-stereo-0/hls-audio-stereo-0.m3u8" -vcodec copy -acodec copy "Nyhetsflödet - Pandemilagen på 60 sekunder.mkv"
```

**Comment by MeSwede** [comment]
Hur kan man extrahera filen "ffmpeg-4.3.1.7z" i Mac OS - vilket program...? Då skapas en fil som heter "ffmpeg" i downloads? Verkar inte som det går att skapa denna fil - behövs mjukvara för detta?

Tack igen!

MeSwede

**Comment by Bub0** [comment]
Testa 7zip.

**Comment by MeSwede** [comment]
7zip for Mac OS?

**Comment by Bub0** [comment]
Sorry visste inte att det inte fanns tillgängligt.
Some suger. ;-)
Första resultatet på goggle gav..... https://osxdaily.com/2010/12/13/open-7z-files-on-a-mac/

**Comment by stefansundin** [comment]
Tydligen har de ett val att ladda ned en zip också, det är nog enklare så behöver du inte ett extra program för att extrahera filen. https://evermeet.cx/ffmpeg/ffmpeg-4.3.1.zip

**Comment by MeSwede** [comment]
Dock, allt gott... Hittade flera 7zip-altenativ... Säkerligen fungerar både 'Keka' och 'The Unarchiver'... Eller? Vi prövar! Självklart fanns redan en zip redan installerad på min MacBook Pro (Mac OS). Prövar vidare! :-)

**Comment by MeSwede** [comment]
Super! :-) Såååååå tacksam - säkerligen ladda ner lite SVTPlay-prylar nu i Lockdon-tider. I övrigt rekommenderas Tunnelblick, för oss som är i utlandet, via Surfshark VPN då mycket program bara kan ses i Sverige!

Igen, så tacksam!

MeSwede

**Comment by MeSwede** [comment]
-> $ via PayPal

MeSwede

**Comment by stefansundin** [comment]
Kanon att du fick det att fungera.
