### ISSUE TITLE
.mkv vs .mp4

### ISSUE THREAD

**Issue by ingemar1961** [stefansundin/privatkopiera#74]
Hej! :-)

Jag har tidigare kunnat privatkopiera videor från t ex SVT Play och fått filer i .mp4 format som passar fint när man ser på dessa i t ex iPhone. Nu kopieras filerna till .mkv format. Någon speciell aledning till detta? Är mkv-formatet bättre och i så fall på vilket sätt?

Med vänlig hälsning

Ingemar1961

**Comment by Bub0** [comment]
Undertexten kan muxas in  imkv måste vara separat i mp4 mkv kan ha många olika spår men det går inte imp4.
Kolla https://github.com/stefansundin/privatkopiera/discussions/57

**Comment by ingemar1961** [comment]
TACK Bub0

**Comment by stefansundin** [comment]
Som Bub0 förklarar så är det främst för att det har bättre stöd för undertexter. Jag borde kanske ha haft en undersökning eller liknande för att kolla om folk har åsikter, men jag kom till slutsatsen att folk kommer nog att höra av sig med klagomål om de har problem. :)

Notera att du kan fortfarande ändra filändelsen till `.mp4` för att få ned filen i det formatet. I det fallet så inkluderas inte undertexten i samma fil. Du kan även ändra filändelsen till `.srt` för att få ned endast undertexten.

Jag har själv inte en iPhone. Fungerar mkv dåligt eller inte alls? Har du några andra besvär?

Kanske borde jag skriva några tips på hemsidan på hur man kan konvertera en mkv fil till mp4, eller åt andra hållet.

**Comment by pflind** [comment]
Varken Mac, iPhone eller iPad stöder MKV, filerna går inte att öppna utan tredjepartsprogram.

De flesta användare kommer ju inte att veta att man kan byta format bara genom att byta filändelse, istället borde det finnas en meny-inställning.

Jag röstar för att göra MP4 som standard då det finns stöd på alla plattformar för formatet.

**Comment by BacchusFLT** [comment]
Jag föredrar absolut MKV. En praktiskt container för både video och
undertexter.

Mitt usecase bygger till 99% på att addera videofilerna jag laddar ner till
mitt repo som hanteras av Plex. I undantagsfall kollar jag på det
nedladdade med VLC. Båda hanterar MKV utmärkt. Jag kör Windows, och har
ingen aning om MKV stöds "native" men tycker det är tämligen ointressant.


Den ons 3 mars 2021 kl 11:24 skrev pflind <notifications@github.com>:

**Comment by stefansundin** [comment]
Jag har funderat lite på det här och jag kommer nog att lägga till en plats i tillägget för inställningar, t.ex. vilken filändelse som är standard. Jag vet inte vad jag sätter som default men jag föredrar nog `mkv` personligen. Funderar på om vi kan komma på nån bra UI som förklarar det hela för användaren.

**Comment by ingemar1961** [comment]
Hej!

Jag föreslår det skapas en listmeny, liknande den som finns vid filterknapparna i Excel. Då kan man enkelt välja filändelse.

Med vänlig hälsning

Ingemar

**Comment by stefansundin** [comment]
I den senaste versionen så kan man nu ställa in standard filändelse. Det defaultar fortfarande till mkv/mka. Hoppas detta räcker som lösning till det här problemet.
