### ISSUE TITLE
URPlay - Error: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by PelEri1** [stefansundin/privatkopiera#75]
Funkar inte med denna video. Vad kan det bero på? Berör det hela URPlay?
https://urplay.se/program/175841-ur-samtiden-boy-s-own-den-brittiska-kulturrevolutionen

**Comment by stefansundin** [comment]
Hej. Verkar som att det där programmet har en vanlig titel men inte en `seriesTitle`, och Privatkopiera hanterar det inte korrekt. Som tur är så verkar det fungera om man fyller in filnamnet manuellt, då kommer kommandot fram. Det verkar som att andra program som är del av serier fungerar korrekt.

Ska fixa det i nästa version. Tack för rapporten.

**Comment by ingemar1961** [comment]
Hej! Det verkar som att menyn i Privatkopiera inte fylls helt med kommandon, text mm för programmet i länken. Privatkopieramenyn fungerar dock med andra program i UR Play.

**Comment by stefansundin** [comment]
> Det verkar som att menyn i Privatkopiera inte fylls helt med kommandon, text mm för programmet i länken. 

Du menar att bara "SD med undertexter" och "SD" visas? Jag tror inte att HD är tillgängligt för detta program.

**Comment by Bub0** [comment]
> Hej! Det verkar som att menyn i Privatkopiera inte fylls helt med kommandon, text mm för programmet i länken. Privatkopieramenyn fungerar dock med andra program i UR Play.

Stefan har ju precis svarat ovanför dig. 🔼

**Comment by Bub0** [comment]
> > Det verkar som att menyn i Privatkopiera inte fylls helt med kommandon, text mm för programmet i länken.
> 
> Du menar att bara "SD med undertexter" och "SD" visas? Jag tror inte att HD är tillgängligt för detta program.

Set är så enkelt som att klicka på SD i rullgardinen  alltså, kanske behövs en liten notis på UR om det.

**Comment by PelEri1** [comment]
> 
> 
> Hej. Verkar som att det där programmet har en vanlig titel men inte en `seriesTitle`, och Privatkopiera hanterar det inte korrekt. Som tur är så verkar det fungera om man fyller in filnamnet manuellt, då kommer kommandot fram. Det verkar som att andra program som är del av serier fungerar korrekt.
> 
> Ska fixa det i nästa version. Tack för rapporten.

Vad blir det för namn man ska fylla i om man gör det manuellt? SD med undertexter funkar.

**Comment by stefansundin** [comment]
> Vad blir det för namn man ska fylla i om man gör det manuellt?

Du kan använda vilket filnamn du vill, men använd filändelsen `.mkv` eller `.mp4`. Efter att jag fixar problemet och släpper nästa version så kommer den automatiskt att använda artikeltiteln, i detta fall `UR Samtiden - Boy's Own - Den brittiska kulturrevolutionen.mkv`.

**Comment by PelEri1** [comment]
https://urplay.se/program/175841-ur-samtiden-boy-s-own-den-brittiska-kulturrevolutionen.mkv

Det där funkar inte. Hur ska man skriva?

**Comment by Bub0** [comment]
> https://urplay.se/program/175841-ur-samtiden-boy-s-own-den-brittiska-kulturrevolutionen.mkv
> 
> Det där funkar inte. Hur ska man skriva?

https://ibb.co/jJtPTwV

**Comment by stefansundin** [comment]
v0.3.4 har nu laddats upp med en fix.

Observera att Chrome har en obligatorisk granskningsprocess för nya versioner. Därför får Chrome uppdateringen först om några dagar.

Uppdateringen borde redan vara tillgänglig i Firefox. Om du fortfarande har den gamla versionen så kan du uppdatera dina tillägg med en knapp på addon-sidan där listan med dina tillägg syns ([se bild](https://user-images.githubusercontent.com/1991151/108611585-c5740080-7394-11eb-8cb6-0a850d19a1b7.png)).
