### ISSUE TITLE
Problem med att ladda ned video med citationstecken

### ISSUE THREAD

**Issue by Preben2** [stefansundin/privatkopiera#77]
Hej Stefan!
Super bra programmering som du gör, efter som mitt tidigare program inte fungera som var Replay Media Catcher 7

Mitt problem gäller

https://www.svtplay.se/video/30178676/gift-vid-forsta-ogonkastet/gift-vid-forsta-ogonkastet-sasong-7-brollopet?start=auto
Avsnitt 1 och 2
Det går ej att ladda ned som föregången 20201-02-18 då gick det fint med avsnitt 1.

Det går bra att ladda ned andra program från svtplay.

Bifogar:
PS C:\> ffmpeg -i "https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-video-avc-4/hls-video-avc-4.m3u8" -i "https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-audio-stereo-1/hls-audio-stereo-1.m3u8" -i "https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/text/text-0.vtt" -vcodec copy -acodec copy "Gift vid första ögonkastet - Bröllopet- "It´s a match, nästan skrämmande".mkv"
ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[hls @ 000002483509f0c0] Skip ('#EXT-X-VERSION:4')
[hls @ 000002483509f0c0] Opening 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-video-avc-4/hls-video-avc-4-1.ts' for reading
[hls @ 000002483509f0c0] Opening 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-video-avc-4/hls-video-avc-4-2.ts' for reading
[https @ 0000024835147e00] Opening 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-video-avc-4/hls-video-avc-4-3.ts' for reading
Input #0, hls, from 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-video-avc-4/hls-video-avc-4.m3u8':
  Duration: 00:43:45.36, start: 0.100000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
[hls @ 0000024836437040] Skip ('#EXT-X-VERSION:4')
[hls @ 0000024836437040] Opening 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-audio-stereo-1/hls-audio-stereo-1-1.aac' for reading
[hls @ 0000024836437040] Opening 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-audio-stereo-1/hls-audio-stereo-1-2.aac' for reading
Input #1, hls, from 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/hls-audio-stereo-1/hls-audio-stereo-1.m3u8':
  Duration: 00:43:45.40, start: 0.057333, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #1:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 194 kb/s
    Metadata:
      variant_bitrate : 0
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x00\x14(
Input #2, webvtt, from 'https://svt-vod-6a.akamaized.net/d0/se/20210217/f5403a1a-0f92-4a0e-b1a7-544dc43f2dca/text/text-0.vtt':
  Duration: N/A, bitrate: N/A
    Stream #2:0: Subtitle: webvtt
[NULL @ 000002483642c080] Unable to find a suitable output format for 'Gift vid första ögonkastet - Bröllopet- '
Gift vid första ögonkastet - Bröllopet- : Invalid argument

Hälsningar
Preben2

**Comment by stefansundin** [comment]
Hej @Preben2.

Problemet här är nog citationstecknen i programmet kombinerat med att du använder Windows. När du klistrar in kommandot i cmd så konverterar den `”` till `"` vilket gör att kommandot blir helt fel där filnamnet ska vara.

Jag ska försöka fixa detta i en uppdatering, men för tillfället kan du testa ta bort bort citationstecknen från filnamnet och försöka igen. Hoppas det fungerar. :)

**Comment by Preben2** [comment]
Tack för ett snabbt svar!

När jag skall ladda ned denna fungera det toppen.
https://www.svtplay.se/video/23934371/din-hjarna/din-hjarna-sasong-1-fysisk-aktivitet?start=auto

ffmpeg -i "
https://svt-vod-7p.akamaized.net/d0/world/20210114/574bc701-68ef-4747-836d-0f5e706efe4a/hls-video-avc-4/hls-video-avc-4.m3u8"
-i "
https://svt-vod-7p.akamaized.net/d0/world/20210114/574bc701-68ef-4747-836d-0f5e706efe4a/hls-audio-stereo-1/hls-audio-stereo-1.m3u8"
-i "
https://svt-vod-7p.akamaized.net/d0/world/20210114/574bc701-68ef-4747-836d-0f5e706efe4a/text/text-0.vtt"
-vcodec copy -acodec copy "Din hjärna - Fysisk aktivitet.mkv"

Det här står i slutet på mitt problem med denna länk
https://www.svtplay.se/video/30178676/gift-vid-forsta-ogonkastet/gift-vid-forsta-ogonkastet-sasong-7-brollopet?start=auto&tab=season-7-2435408#section-season-7-2435408


[image: image.png]
  Som jag skrev fungerade det jo 2021-02-18 att ladda ned avsnitt 1

Super bra att du finns, jag hoppas att du hittar felet.

Ha en trevlig Helg

/Preben2

Den fre 26 feb. 2021 kl 19:51 skrev Stefan Sundin <notifications@github.com

**Comment by stefansundin** [comment]
@Preben2 Din bild fungerade inte tyvärr. Förmodligen går det inte att lägga till bilder via e-post.

**Comment by stefansundin** [comment]
Har nu släppt v0.3.5 där detta hanteras genom att en hel drös olika citationstecken (`"”´‘’`) nu ersätts med ett enkelt citationstecken (`'`). 54e05d7230b292c4738a3e0ebc242045ee541770

Om du fortfarande har problem efter uppdateringen så öppna gärna tråden igen. Tack!

https://github.com/stefansundin/privatkopiera/blob/679527615c33aab32502b09f07cc978376009df3/extension/js/popup.js#L99
