### ISSUE TITLE
svtplay.se/klipp fungerar ej

### ISSUE THREAD

**Issue by PelEri1** [stefansundin/privatkopiera#78]
"Fel: Den här hemsidan stöds ej."

Så står det när man försöker plocka dessa filer. Varför är det så?
https://www.svtplay.se/genre/svt-sport-forklarar

**Comment by Bub0** [comment]
Gå in på klippet du vill ha...

**Comment by stefansundin** [comment]
Hej @PelEri1.

Du måste klicka in dig till videon du vill ladda ned. Privatkopiera kan för tillfället inte hjälpa dig att ladda ned en hel genre.

**Comment by Bub0** [comment]
> Hej @PelEri1.
> 
> Du måste klicka in dig till videon du vill ladda ned. Privatkopiera kan för tillfället inte hjälpa dig att ladda ned en hel genre.
> 
> Jag borde kanske ha ett bättre felmeddelande i det här fallet.

Jag trodde också Seth cat så enkelt som att gå in på något klipp först..... Men även om man gör det kommer meddelandet.

**Comment by stefansundin** [comment]
Ah. Jag ser felet. I senaste uppdateringen så stöds bara `/video/` och här används `/klipp/`. Det är nog en enkel fix, ska kolla närmare snart.

**Comment by stefansundin** [comment]
Detta är nu fixat i v0.3.5. 97df9e48900b44e01b4906b004a1da652f51c10b

Tack för rapporten @PelEri1.

**Comment by jonas9881** [comment]
@stefansundin hej!

Det funkar inte, iallafall inte denna: https://www.svtplay.se/klipp/eZYdw7b/smygtitt-ta-det-som-en-man?info=visa
eller denna: https://www.svtplay.se/klipp/8zXaX5X/trailer-dokument-inifran-arvet-och-tystnaden?info=visa&tabs=season-0-KQzrZrB

Beror det på att SVT har ändrat från siffror till bokstäver efter ordet "klipp" i URL:en?
eller att tillägget inte funkar som det ska och behöver en uppdatering för att svt har ändrat sitt system?

Tacksam för svar!

MVH/ Jonas

**Comment by stefansundin** [comment]
@jonas9881 Tjena. Nu såg jag inte detta innan jag släppte v0.3.8 så tyvärr så testade jag inte det i tid. Det fixas i nästa version.

Tills dess så kan du använda denna workaround: Byt ut `/klipp/` till `/video/` i URL:en. Sen ska det fungera med v0.3.8. T.ex. https://www.svtplay.se/video/eZYdw7b/smygtitt-ta-det-som-en-man?info=visa
