### ISSUE TITLE
502 ERROR on all  TV4Play

### ISSUE THREAD

**Issue by Bofinken** [stefansundin/privatkopiera#8]
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
For more information on how to troubleshoot this error, please refer to the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html).

**Comment by bjoh5107** [comment]
Same for me.

**Comment by stefansundin** [comment]
Har inte haft tid att titta på detta än. Förhoppningsvis i veckan.

**Comment by stefansundin** [comment]
Fixat i https://github.com/stefansundin/privatkopiera/commit/8d4bcf4c326d0de21987e9caa193c16b15415c7b och v0.1.7.
