### ISSUE TITLE
Tv4play har helt slutat fungera. :-(

### ISSUE THREAD

**Issue by Bub0** [stefansundin/privatkopiera#9]
Strax innan stod det 502 error men nu verkar det helt dött :-(

**Comment by stefansundin** [comment]
Har inte haft tid att titta på detta än. Förhoppningsvis i veckan.

**Comment by stefansundin** [comment]
Fixat i https://github.com/stefansundin/privatkopiera/commit/8d4bcf4c326d0de21987e9caa193c16b15415c7b och v0.1.7.
