### ISSUE TITLE
Urplay fungerar inte med chrome

### ISSUE THREAD

**Issue by Bagfields** [stefansundin/privatkopiera#93]
kopiering av https://urplay.se/program/217042-mitt-ar-med-hudcancer?source=kunskapskanalen.se fungerar inte i chrome men fungerar i firefox
Det är chrome i Lubuntu 20.4.

**Comment by Bub0** [comment]
Går bra här. :-)

**Comment by Tigerfluga** [comment]
Jag har också problem. Det står bara att den laddar och mer händer inte.

**Comment by stefansundin** [comment]
Hej. Släpper ny version inom kort som fixar UR och NRK.

**Comment by stefansundin** [comment]
Nu är v0.3.7 släppt och det ska fungera igen. Det kan ta ett tag innan uppdateringen godkänns för Chrome, men det är redan ute till Firefox.
