### ISSUE TITLE
Direktsändningar SVT Fungerar inte.

### ISSUE THREAD

**Issue by Tigerfluga** [stefansundin/privatkopiera#97]
Har problem när jag laddar ner direktsändning från SVT.
Det blir osynkat mellan ljud och bild när man tittar på det man har laddat ner.

**Comment by Ordval** [comment]
Jag har ingen lösning på ditt problem, men jag ser, 
speciellt på SVT 1, att de nuvarande fasta direkt-
strömmarna (efter omläggningen - hoppas på att få 
tag i några med högre bithastighet)   sändningarna 
ibland diffar mellan -3,2 till -6,2 sek., frågan är om 
det ens har med tilläggsprogrammet att göra 
överhuvudtaget, och skall det göras någon 
modifikation betyder ju det att Stefan måste knåpa 
ihop någonting som känner av hur stor diffen är 
vid det precisa tillfället. 

Får du alltid dessa osynkade problem ?

**Comment by Tigerfluga** [comment]
Det brukar bli varierat resultat.

**Comment by Tigerfluga** [comment]
Det uppträder sporadiskt.

**Comment by Ordval** [comment]
Precis som det blir för mig när jag tittar på 
strömmarna genom Streamlink som reläar till VLC. 
Precis just nu för ögonblicket stämmer synkningen 
för Svt 1 både genom hemsidan och Streamlink. 

Jag tror fortfarande att när det blir osynkat i 
nedladdningarna kan man bara välja att försöka 
räkna sekunder och sedan ställa in synkningen i t.ex. VLC.
